### ISSUE TITLE
Change event naming from jQuery style namespace "<event name>.htmx" to "htmx:<event name>"

### ISSUE THREAD

**Issue by sirinath** [bigskysoftware/htmx#109]
Instead of `event.htmx` have `htmx.event`. E.g. instead of `afterOnLoad.htmx` have `htmx.afterOnLoad`. This is more natural to read especially when it comes to Hyperscript.

Maybe this can be restricted to Hyperscript which can have this convention of `namespace.event`

**Comment by keyurshah** [comment]
agree with this, this stood out to me as well as being a bit harder to read. Thanks

**Comment by chg20** [comment]
It annoys me too.

This comes from jQuery, where the namespace is *after* the event name:

https://www.w3schools.com/jquery/event_namespace.asp
https://www.learningjquery.com/2007/09/namespace-your-events
https://stackoverflow.com/questions/21817397/event-handler-namespace-in-vanilla-javascript

I picked this up because bootstrap was (and still is) doing it this way:

https://getbootstrap.com/docs/3.3/javascript/#modals-events

The namespace for these events is `bs.modal`

I don't have strong feelings on this and as near as I can tell this is a purely jQuery artifact, but I'm worried that I'm missing some functionality if I switch things up.  Anyone know anything more on this?

**Comment by chg20** [comment]
According to a comment on this page: https://css-tricks.com/namespaced-events-jquery/

I could use

`htmx:eventName`

which I would *love*.  That dovetails perfectly with a feature I am planning on adding to hyperscript.

![image](https://user-images.githubusercontent.com/469183/85435986-249b2000-b53d-11ea-944c-d7649115514f.png)

**Comment by chg20** [comment]
OK, after a lot of digging, the colon syntax will *not* work with the jQuery namespace concept.

But, since htmx does not depend on jQuery, perhaps this is the time to undo that decision.

As a bonus, zepto.js *does* use the colon syntax:

http://intercoolerjs.org/docs.html#zepto

@bencroker do you have an opinion on this?

**Comment by bencroker** [comment]
The `eventName.htmx` did strike me as strange at first, so I'm glad to see that this is being reconsidered. I find `htmx.eventName` an improvement, however `htmx:eventName` would be my personal preference.

**Comment by sirinath** [comment]
One other thing to consider is can we also have `namespace1:namespace2: ... :namespacen:event` so a group of events can be selectively turned on and off.

**Comment by chg20** [comment]
@sirinath I think that with this new naming scheme it will be harder to turn namesapces on and off, right?  

jQuery supports that but it looks like internally they do all sorts of crazy state retention to make it work.

**Comment by sirinath** [comment]
If this can be simply done without much runtime overhead perhaps do it otherwise drop it.

**Comment by chg20** [comment]
fixed with https://github.com/bigskysoftware/htmx/commit/4f3cf2d889ff549422ed2bb135fc5775f7e54dab

**Comment by bencroker** [comment]
Nice!
