### ISSUE TITLE
hx-params do not takes into account other parameters

### ISSUE THREAD

**Issue by tsowa** [bigskysoftware/htmx#1150]
According to this documentation: https://htmx.org/attributes/hx-params/
hx-params should add the rest of the parameters when creating a request.

Sample:
```
<form>
	<input type="hidden" name="foo" value="bar">
	
	<input
		type="text"
		name="description"
		hx-get="/mycontroller"
		hx-trigger="keyup changed delay:600ms"
		hx-params="*"
		>
</form>
```
On the server side I am receiving only the description parameter: /mycontroller?description=abcccgsdf
If I change hx-params to hx-params="description,foo" I am receiving: /mycontroller?description=abc&foo=undefined

It seems to be a bug.

**Comment by David-Guillot** [comment]
`hx-params` is about filtering parameters that can be found _within_ the element triggering the request. This is why hx-`params="description,foo"` sends `foo=undefined` and not `foo=bar`. htmx searches for a `foo` field _within_ the `description` field, and that returns `undefined`.

If you want to send to your server values that are outside the element triggering the request, you can use [hx-include](https://htmx.org/attributes/hx-include/).

Otherwise you can move your htmx logic to the `<form>` and by default get all input elements values sent.

**Comment by laheadle** [comment]
The docs for hx-params don't specify this behavior.

**Comment by 1cg** [comment]
The docs say this:

> The hx-params attribute allows you to filter the parameters that will be submitted with an AJAX request.

Which is what this (of limited use) attribute does.

**Comment by kg-currenxie** [comment]
> The docs say this:
> 
> > The hx-params attribute allows you to filter the parameters that will be submitted with an AJAX request.

And how are we supposed to understand what `the parameters` is referring to, and that it's looking within an element? What's the point of docs that nobody understands.. hence why this issue was created in the first place.
Maybe rather than just replying what the docs already says, think about clarifying the docs instead?

**Comment by andryyy** [comment]
It can only apply to parameters of form data that is being processed.

You cannot have any processed form data of an outside element without including it first. Including outside elements happens before data processing.

Form data consists of parameters followed by their corresponding value. 

A parameter is not a specific element defined in the DOM.

A small example of selecting a parameter from a form with two inputs would probably do it.

Feel free to add it.
