### ISSUE TITLE
htmx request doesn't launch when used with <form> and hyerpscript disable<button> on Chrome

### ISSUE THREAD

**Issue by delzac** [bigskysoftware/htmx#1171]
```
<form hx-post="/clicked" hx-confirm="hello">
    <button type="submit" class="btn btn-primary" _="on click toggle @disabled until htmx:afterOnLoad" >Save</button>
</form>
```
Using the above code, when you click on the `save` button, the buttons is `disabled` but no htmx request is launched.

To replicate this bug use:
htmx - 1.5.0 (also tested on 1.8.4)
hyperscript - 0.9.1
browser - chrome and edge

This bug doesn't seem to affect Firefox browser.

**Comment by delzac** [comment]
I believe this issue is the same as #1063

**Comment by 1cg** [comment]
can you change your hyperscript to this:

```applescript
on click wait a tick then toggle @disabled until htmx:afterOnLoad
```

I'm pretty sure chrome is detecting that the button is disabled an not propagating the `click` event, which means htmx isn't seeing it.  By waiting a tick you should let the click event process and then disable the button.

That's my guess.

**Comment by 1cg** [comment]
i put together a demo and I think the problem is that you aren't listening for the `htmx:afterOnLoad` from the form, you are listening on the button (on which the event isn't fired: the events are fired on the element that triggers the request).

This demo works for me in Chrome and Firefox:

https://codepen.io/1cg/pen/ZEjOLjb?editors=1001

So I think this is working.

By the way, there are two extensions you may want to check out that are related to this:

https://htmx.org/extensions/disable-element/

https://htmx.org/extensions/loading-states/
