### ISSUE TITLE
Update docs/#parameters with note about button values

### ISSUE THREAD

**Issue by EdGuiness** [bigskysoftware/htmx#123]
EdGuiness wrote:

Reading the [docs](https://htmx.org/docs/#parameters) I note that
 
>...an element that causes a request will include its value if it has one...

So therefore I had expected this...

```html
        <button hx-post="serverAction"
                hx-target="closest .insert-me"
                hx-swap="afterbegin"
                value="abc"
                class="btn btn-primary btn-sm">
```

...to send the value "abc" to the server in Form data, but it doesn't?

What I do see is a header `hx-active-element-value` containing the "abc" value.

chg20 replied:
> Yeah, buttons are a little tricky
> The way that forms work is that on submit they will include the clicked button value, but that is hard to do consistently from a dynamic ajax context
>... to complete the thought: since I didn't feel I could consistently provide the value for buttons in all expected contexts, I chose to provide the active element (the usual hack work around for this button problem) as exactly that: the active element, so that there is truth in advertising.

**Comment by bencroker** [comment]
@1cg It makes sense to me that "submitter" types should be ignored from form submission requests, but if the button is the element that triggers the request, should its value not be included?
https://github.com/bigskysoftware/htmx/blob/v0.0.8/src/htmx.js#L1174-L1177

**Comment by 1cg** [comment]
The problem is that would include the value of all buttons, not just the one causing the submission, which is the normal behavior on form submits.

**Comment by bencroker** [comment]
Couldn't we exclude all buttons _except_ for the one that triggered the event?

**Comment by lachlancotter** [comment]
I find it counterintuitive that HTMX does not send the value of the submitting form element in the request. This is a departure from the HTML standard.

The HX-Active-Element header is also problematic. It appears to depend on `document.activeElement`, which tracks element with keyboard focus. However, focus tracking is not implemented consistently across browsers.

For example, Chrome gives focus to form buttons when clicked, while Safari and Firefox do not.

This article gives a good analysis of the differences:
https://zellwk.com/blog/inconsistent-button-behavior/

The result is, if you're depending on HX-Active-Element to know which button the user clicked, you will not get consistent behaviour across browsers without custom workarounds.

The article I referenced above suggests a simple fix.

Perhaps HTMX could adopt a similar strategy, or use some other method to include the value of the clicked button in form requests. Otherwise, it's breaking a fairly basic standard behaviour of HTML forms.

**Comment by 1cg** [comment]
Behold, the horror:

https://stackoverflow.com/questions/2066162/how-can-i-get-the-button-that-caused-the-submit-from-the-form-submit-event

**Comment by 1cg** [comment]
Here is some potential code that might be used as a basis for including the button value.

I would do it a bit differently, storing the value on the enclosing form, but same idea.

```js
!function(){
    var lastBtn = null
    document.addEventListener('click',function(e){
        if (!e.target.closest) return;
        lastBtn = e.target.closest('button, input[type=submit]');
    }, true);
    document.addEventListener('submit',function(e){
        if ('submitter' in e) return;
        var canditates = [document.activeElement, lastBtn];
        for (var i=0; i < canditates.length; i++) {
            var candidate = canditates[i];
            if (!candidate) continue;
            if (!candidate.form) continue;
            if (!candidate.matches('button, input[type=button], input[type=image]')) continue;
            e.submitter = candidate;
            return;
        }
        e.submitter = e.target.querySelector('button, input[type=button], input[type=image]')
    }, true);
}();
```
The problem with this (and any other) approach is that it is hard to guarantee that it works in all browsers, and there can be serious consequences if it does not work.  Consider a form that has two buttons:

* Save
* Cancel

If you don't properly report that the cancel button was clicked on a submission... bad news.

**Comment by 1cg** [comment]
This is why, in general, I would recommend allowing the save button to trigger a `submit` and then having the cancel button have its own `hx-get` attribute, so that the two are not conflated.

Still, I'd like to do the right thing if it can work cross browser.

**Comment by spookylukey** [comment]
This is particularly an issue for `hx-boost`, since the form data is now quite different. If you have multiple buttons in a form or page that go to the same endpoint, and the endpoint tries to use form data to see which button you pressed, boosting will fail badly. At the very least this should be documented in the "Boosting" docs.

There is also a safe-ish way to implement this server side if you are worried about the edge cases where browsers are not reporting which button is pressed - you do:
```
if save_button_pressed:
    save()
elif cancel_button_pressed:
    cancel()
else:
    do_nothing()
```
i.e. don't assume a default button.

**Comment by 1cg** [comment]
@spookylukey that's a really good point

I've been putting off dealing with this for a long time because it seems like there isn't a clean solution, but it does need to get solved.

What about this logic:

On a form that will trigger on submit, we add a click and focus listener for all sub-elements.  If a click comes from a button, we record the button value, on non-button focuses we clear the value.  On submission, we include the last clicked button value if it exists.

In this manner, if someone clicks a button but it is cancelled for some reason, and then submits in another way (e.g. tabbing into an input and hitting enter) we won't include a spurious button value.

Still thinking about it, but this needs to work.

**Comment by 1cg** [comment]
in the next release we will include the value of the clicked button in forms
