### ISSUE TITLE
hx-trigger inheritance and active search pattern

### ISSUE THREAD

**Issue by daaku** [bigskysoftware/htmx#1501]
I'm not sure if I'm missing something, but the pattern I'm trying to use is:

1. There'a s `<form>` with a number of controls, mostly `<select>`s
2. There's a `<input type=search>`.

The parent `<form>` has a number of parameters:
```html
<form
  hx-get="{{ action }}"
  hx-target="#results"
  hx-select="#results"
  hx-swap="outerHTML"
  hx-trigger="change"
  hx-push-url="true">
```

This works well for the `<select>`s and the trigger works as expected.

The `<input type=search>` follows the [active-search](https://htmx.org/examples/active-search/) example, but combined with [inheritance](https://htmx.org/docs/#inheritance) for most of the attributes. Only the `hx-trigger` should be different:
```html
<input type="search"
       class="form-control"
       placeholder="Search"
       name="text"
       value="{{ text }}"
       hx-trigger="keyup changed delay:200ms, search">
```

But it seems like the search input still only triggers on a change event. It doesn't trigger on the keyup event. This _can_ be fixed by duplicating all the attributes from the `<form>`.

What is the expectation here? Is this working as intended or is the inheritance buggy here?

<details>
  <summary>Markup Sample</summary>

```html
<form
  hx-get="/transactions"
  hx-target="#results"
  hx-select="#results"
  hx-swap="outerHTML"
  hx-trigger="change"
  hx-push-url="true"
  class="row gy-2 gx-3 align-items-center mb-3"
>
  <div class="col-auto">
    <input type="search"
           class="form-control"
           placeholder="Search"
           name="text"
           value=""
           hx-trigger="keyup changed delay:200ms, search">
  </div>
  <div class="col-auto">
    <select name="category" class="form-select">
      <option value="">All Categories</option>
      <option value="Ent">Ent</option>
```
</details>

**Comment by Telroshan** [comment]
Hey, I think this is a similar confusion as in #1424

Even though [the attribute inheritance doc](https://htmx.org/docs/#inheritance) says the following:
> **Most** attributes in htmx are inherited

The [hx-trigger](https://htmx.org/attributes/hx-trigger/) doc says:
> `hx-trigger` is not inherited

The [hx-get](https://htmx.org/attributes/hx-get/) doc says:
> `hx-get` is not inherited

So what's happening there? It's easy to get confused between attributes inheritance and event bubbling.
- You define `hx-get` and `hx-trigger` on the form
- When you make a change in the input, the `change` event is fired, and even though the hx attributes are not inherited, the change event itself [bubbles](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#event_bubbling)
- So the form's hx-get is triggered, because the `change` event was fired in a child, bubbled, then was also fired for the form itself

Whereas, for keyup and search events:
- You define `hx-trigger` on the search input itself, so this only applies to the input itself, not the parent form that already has its own `hx-trigger` defined
- The events `search` or `keyup` are fired on the input as you play with it
- Those events also bubble, but since the form didn't define a `hx-trigger` on them, nothing happens

So in your case you might:
- Copy the attributes that are not inherited (hx-get and hx-trigger only, the others are inherited) to your search input, which is the easiest way
- If you really don't want to copy the hx-get/trigger specifiers, you could also add some custom JS that listens for search/keyup events on the search input, and manually trigger an event on the form using [htmx.trigger](https://htmx.org/api/#trigger)
- I guess you could also use hyperscript there to achieve the same result as the previous option I mentioned, without writing JS

(I'd strongly suggest the first option, but it's up to you!)

**Comment by daaku** [comment]
Ah, I understand the core issue that `hx-get` isn't inherited. `hx-trigger` not being inherited isn't an issue for my case (nor is the cause of my problem).

I did try one more thing, but it only partially worked (the search event works, but the keyup doesn't):
```html
hx-trigger="change, keyup changed delay:200ms from:find [type=search], search from:find [type=search]"
```

As I debugged option 1, I realized it loses all the other form data. So I think option 2 is the way to go for me.

Thanks for the insanely quick response!

**Comment by daaku** [comment]
Interesting, removed `changed` makes my updated trigger work as I expected (sans the changed behavior):
```html
hx-trigger="change, keyup delay:200ms from:find [type=search], search from:find [type=search]"

```

**Comment by daaku** [comment]
Closing as I think there's a working solution and the issue as described was a misunderstanding of the functionality. If the `changed` issue is a real bug another issue probably will be more appropriate.

**Comment by Telroshan** [comment]
Oh, neat! I had completely forgotten about the `from` specified in hx-trigger, that's indeed a way better solution!

About the form data being lost, you could also use [hx-include](https://htmx.org/attributes/hx-include/), such as `hx-include="closest form"` that, if placed on your search input, will include any input value from your form in the request

The `changed` issue looks like a bug to me, from the top of my head, since the from specifier should make it act as if the hx-trigger was defined on the element itself. Will need some investigation to make sure

**Comment by daaku** [comment]
Ah, `hx-include` seems like a good solution too. Just tried it and works as advertised.
