### ISSUE TITLE
Built Toolchain?

### ISSUE THREAD

**Issue by benpate** [bigskysoftware/htmx#151]
So I submitted my first pull request (yay!) and am working on another.  I've noticed myself missing a number of pieces of infrastructure that I'm used to having around on other projects.  I'm **usually not in favor** of big, complicated toolchains for building Javascript projects.  Less is more.  But here is a short list of some tools that have really helped me in the past.  

Are these being considered for the future 1.0 release?

**Minification** 
I like [rollup](https://rollupjs.org/) because it's a little more modern than [WebPack](https://webpack.js.org/).

**Linting Tool**
I like [tslint](https://github.com/palantir/tslint) because of Typescript (see below) but any solid linter would do.

**Typescript**
I know this is a big one, and controversial with many Javascript developers.  Typescript has helped me catch so many errors before they even get saved.  It's been great for self-documenting code, and automatically identifying edge cases (like unhandled null values) that are easy for humans to miss.  I could go on, but I'd strongly encourage making a branch to explore building/transpiling the core HTMX files with Typescript.

--
Rolling out things like this has consequences for every person who touches the code, so it should be much more of a discussion than a pull request from a newbie.  But, I'll throw out a few suggestions to see what makes sense to the powers that be :) And, if there's a decision/consensus from you all who've actually been doing this for a while, I'd be happy to volunteer to do a bunch of the work.

**Comment by 1cg** [comment]
Hi @benpate,

I'm happy to have someone improve the build chain.  Broadly speaking I would prefer to have as simple a build chain as possible for htmx.  I don't like the javascript UMD stuff and I would prefer to write javascript in the idiosyncratic manner that I have been, as a global object.  I don't mind small transformations for generating a UMD or alternative final product, as long as it is small.  The closer the /src version is to the /dist version, the better IMO.

Typescript is an interesting idea, but with the test suite I don't think matters as much.  I like type systems mainly for auto-complete and WebStorm does a pretty good job in javascript.  In general I would prefer a typed language to work in, but since we end up producing javascript anyway, I lean towards just dealing with the many, many warts of that language.

All that being said, the hyperscript project seems like it would be much more amenable to a more elaborate build system and potentially using TypeScript:

https://github.com/bigskysoftware/_hyperscript

Any interest in working on that?

**Comment by benpate** [comment]
Hey, thanks for responding (esp when you're swamped).

I think I agree with everything you put here, and there's limited value in simply adding shiny new tools.  I also think the overall style inside HTMX is pretty cool, and it would be a loss to try changing it.  My favorite "build chain" was simply Typescript, then upload everything up for the CDN to handle the rest -- it was glorious :)

I'll take a look at Hyperscript if you think that's a better place to start.  I'm not too familiar with it yet, but adding a Typescript compiler *should* not be difficult.  I love it because the autocomplete and static analysis are outstanding -- though I haven't tried WebStorm as a comparison.  A proof of concept should be simple, but a real conversion will take a little bit of coordination, mostly because renaming files to "*.ts" could conflict with other pull requests happening at the same time.

**Comment by 1cg** [comment]
Closing out as I want to keep htmx toolchain free for now.
