### ISSUE TITLE
Proposal: config to disable/customize attribute inheritance

### ISSUE THREAD

**Issue by metametadata** [bigskysoftware/htmx#1520]
Even though inheritance allows writing more concise code in typical cases, I'd strongly consider turning it off in my projects.

I find it difficult to reason about code because of inheritance when there are nested elements which have different `hx-` attributes and it all behaves in unexpected way. It's extra non-trivial because not all attributes are inherited (for example, `hx-post`), so I have to check the documentation for that additionally.

I've tried `hx-disinherit="*"` but it seems to have an effect only on immediate children. I.e. I can't set it in `body` to get what I want.

Idea: add an extension or a new attribute to disable inheritance in all the children of the element, their children, etc. For example, it could be an attribute `hx-recursive-disinherit="*"`.

And then I'd likely want to keep inheritance of, say, `hx-ext="morph"`. So the new toggle should also support more fine-grained configuration, e.g. something like `hx-recursive-disinherit="not hx-ext, not hx-some-other-inherited-attr, hx-some-attr-which-should-be-disinherited"`.

**Comment by alexpetros** [comment]
This came up in the discord too. The basic proposal is to add an attribute that either lets you disable inheritance globally, or specify which attributes are inherited by default:

```
// Disable all inheritance
htmx.config.implicitInheritance = false

// Enable it for certain attributes by default
htmx.config.implicitInheritance = ['hx-disable', 'hx-boost']
```

cc @gnat @1cg

**Comment by th3n3rd** [comment]
The main issue I face is that I found it counter-intuitive that moving a piece of html around does change it's behaviour, it makes refactoring a lot harder for no good reason.

I think the current behaviour breaks the [Locality of Behaviour](https://htmx.org/essays/locality-of-behaviour/) the author advocate for so much. For instance I cannot just work with fragments, which are typically separated pieces of code that live on their own, I often need to know more, e.g. their surrounding, in order to understand the fragment behaviour.

Also IMHO increases the likelihood of introducing undesired bugs, i.e. somebody adding a new query parameter in the url or somebody excluding some parameters in the parent without knowing it will affect fragments living elsewhee.

**Comment by andryyy** [comment]
It is not always inconsistent because it does not fit your use case. The LoB is not broken here imo, it just does not behave like you want or need it to behave. 

If you want a fragment to only apply to whatever function it has, it can be configured to do so. When inserting the fragment you could pass parameters to the fragments in the template (if any). Or use includes, params, vars…

Can you post one or more examples where you struggle?

**Comment by Telroshan** [comment]
Closing this as since this issue was opened, `htmx.config.disableInheritance` is now a thing, see the [attribute inheritance](https://htmx.org/docs/#inheritance) section in the docs!
