### ISSUE TITLE
Issue with multiple HX-Trigger events from server.

### ISSUE THREAD

**Issue by cbmeeks** [bigskysoftware/htmx#1889]
I have a controller that sends a custom event down to the client when there is an error.

![image](https://github.com/bigskysoftware/htmx/assets/49341/f4ce5256-a6f3-46d5-8276-d0ac11bc3bce)

As you can see, the event takes a parameter that is the name of the field that caused the error. 

This results in the following HTMX error:

![image](https://github.com/bigskysoftware/htmx/assets/49341/ea9423c6-170c-4ba5-8c01-d8db9005dd79)

Now, if I only send ONE event, it works just fine.

This WORKS:

![image](https://github.com/bigskysoftware/htmx/assets/49341/2f9961f6-c77f-4302-aef3-e1cd86790861)

Then I thought maybe it didn't like multiple TX-Trigger headers so I then placed two of them in a comma-separated string.  But this gives me the same error:

![image](https://github.com/bigskysoftware/htmx/assets/49341/57824d49-35fc-4d67-aaf4-ce000e731789)

Now, I can pass multiple events down just fine as long as they don't pass an argument with it (in JSON format).
For example, this works fine:

![image](https://github.com/bigskysoftware/htmx/assets/49341/de9f8632-7131-4405-85b0-8c87e4ac98e8)

That will fire the event twice.

It seems that if the custom event contains a JSON-formatted object with a parameter, it throws an exception on the client.

Is there a better way to handle this?  I essentially need to pass a list of strings down to my client for a custom event.

Thanks.

**Comment by andryyy** [comment]
Hi,

Can you check in the dev console what the response headers look like?

It needs to be escaped JSON, like:

```
{
  "name": "hx-trigger",
  "value": "{
    \"showAlert\": {
      \"validationError\": {
        \"locations\": [
          [\"name\"]
        ],
        \"message\": [
          \"String should have at least 1 characters\"
        ]
      }
    }
  }"
}
```

**Comment by cbmeeks** [comment]
Oh, that makes sense.  I totally didn't catch on to that.
That fixed the JS error.  No more errors!

However, it only actually fired the SECOND event.  Not both of them.

![image](https://github.com/bigskysoftware/htmx/assets/49341/9d70e1bd-1a86-442a-8520-df5e5baa7c89)

I would think the event would fire twice (one for "newFirstThird" and again for "newBranch").  But only the "newBranch" trigger ran.

**Comment by Telroshan** [comment]
Hmm testing the following in the browser's dev console:
```js
JSON.parse(`{"reportError": "newFirstThird", "reportError": "newBranch"}`)
```
Indeed only returns the following
```json
{
    "reportError": "newBranch"
}
```
I guess that's because you can't have 2 values with the same key in a JSON object (or in any key-value pair system really)

Since the value associated to an event name is some detail that you pass to the client and let the client handle on its own, why not use an array in this case ?
So, instead of generating this `{"reportError": "newFirstThird", "reportError": "newBranch"}` JSON, you could generate the following: `{"reportError": ["newFirstThird", "newBranch"]}` and loop through that array on your client implementation

**Comment by cbmeeks** [comment]
That's a good idea.  I will try that.  It won't be hard to handle the client code.  At the end of the day, I just wanted a way to grab some text fields and change their class from the server without having a custom event for every field.

Thanks for your help!

**Comment by cbmeeks** [comment]
Converting to an array worked.  Thanks again for the help.  The JSON parsing problem I had makes sense as well.

**Comment by rikbosch** [comment]
I've come across the same issue where our server returns multiple hx-trigger headers when there are multiple events to trigger. 

I think it is a small change to support multiple hx-trigger headers using `getAllResponseHeaders()` instead of `getResponseHeader()`. I'd be willing to try and make the this change if it's helpful? Please let me know.

**Comment by timo95** [comment]
I am having the same problem. Support for multiple json headers would be very helpful for me.
