### ISSUE TITLE
Button’s hx-vals not sent. When defined on the Form, Button’s hx-vals don’t override the Form’s

### ISSUE THREAD

**Issue by JanRomero** [bigskysoftware/htmx#1940]
According to the docs, `hx-vals` is inherited and can be overridden by children.

I’m trying to do the following, with the aim of every button sending its own values to a common endpoint, without having to repeat the endpoint (and other inheritable stuff) for each button:

```HTML
<form hx-post="/my/page">
    <button hx-vals='{"id": 1055}'>One Button</button>
    <button hx-vals='{"id": 1675}'>Another Button</button>
</form>
```

When clicking one of the buttons, HTMX does send a POST request to the specified endpoint, but it does not send *any* values. Am I being stupid for expecting this to work?!

When I specify values on the form, HTMX sends those, they *do not* get overridden. I.e. all buttons send `id=0` here:

```HTML
<form hx-post="/my/page" hx-vals='{"id": 0}'>
    <button hx-vals='{"id": 1055}'>One Button</button>
    <button hx-vals='{"id": 1675}'>Another Button</button>
</form>
```

I can only get this to work by repeating `hx-post` for every button, which I would like to avoid.

For the record, this works, but IRL I want to send more than one value:

```HTML
<form hx-post="/my/page">
    <button name=id value=1055>One Button</button>
    <button name=id value=1675>Another Button</button>
</form>
```

Thanks you!

**Comment by Telroshan** [comment]
Hey, it's actually the expected behaviour
`hx-vals` is evaluated relatively to the element that triggers the request, i.e. whichever element defines the `hx-post`. So in that case I think you would have no other choice than indeed repeating hx-post on each button.

If that can work for you though, you may want to use standard [name/value attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#name) on your buttons, which will only include in the payload, the value of the clicked button and not any other's one. You could then keep the hx-post on your form, as well as a hx-vals for any inheritable stuff as you were mentioning.
Note you could also use say hidden inputs along hx-include to carry some values to inherit around, rather than hx-vals (just mentioning that option in case you had missed it)

See [this JSFiddle](https://jsfiddle.net/megtfcxv/) with an example, see how clicking on a button sends its value as you would expect
