### ISSUE TITLE
Excluded attributes when cloning

### ISSUE THREAD

**Issue by bencroker** [bigskysoftware/htmx#195]
There are only two attributes that are excluded when cloning:
```js
var EXCLUDED_ATTRIBUTES = ['id', 'value'];
```

This is resulting in checkboxes flickering when swapped in as the settle delay is applied to the `checked` attribute. I wonder whether `checked` and `selected` should be added to `EXCLUDED_ATTRIBUTES` or whether it would make sense to _only_ clone the `class` attribute?

![ScreenFlow](https://user-images.githubusercontent.com/57572400/93056117-40a9eb80-f66c-11ea-9cc4-4e41ffdc01bf.gif)

**Comment by 1cg** [comment]
I''ve thought about that: making it a whitelist rather than a blacklist.

I ran into issues w/ the `@` based attributes in AlpineJS too.

I think we'd want to at least include the following attributes:

```
  class, style, width, height
```

Any others you can think of?  I can make it part of `htmx.config` so if someone wants to add additional attributes they can.

**Comment by bencroker** [comment]
Perfect, thanks!

**Comment by bencroker** [comment]
Any chance you might consider renaming the `attributesToSwizzle` config setting to `attributesToSettle`? Introducing new nomenclature means having to write new docs, whereas the concept of settling is already explained and used as a modifier.

**Comment by 1cg** [comment]
:us: :disappointed: 

https://github.com/bigskysoftware/htmx/commit/5444ce598b21c275125a9d646e9d14175384efa0

**Comment by bencroker** [comment]
:pray:
