### ISSUE TITLE
HTMX requests takes >5s just to reach django backend

### ISSUE THREAD

**Issue by Sadeeed** [bigskysoftware/htmx#1958]
I am trying out HTMX for the first time and It has been a very fun experience but for some reason, every request I make through HTMX takes a long time just to reach the backend as compared to a similar fetch request or even a simple form submission and I can not figure out why that is.

Just to clarify, I'm not talking about the response from the backend that takes its time depending on what it's doing but when I make a request from the frontend / HTML template it has always been received instantaneously but with HTMX i'm sometimes sitting for more than 30s before a request is received.

Any kind of help would be great.

Here's some example code:

**views.py**
```py
class CreateArticleView(TemplateView):
    template_name = 'snippets/monetizable_items.html'

    def post(self, request, *args, **kwargs):
        content = request.POST.get('content')
        article = Article.objects.create(content=content)
        context = {'article': article}
        return render(request, self.template_name, context)
```
        
**index.html**
```html
<div class="container my-5">
    <div class="cont-wrap">
        <form id="article-form" hx-post="{% url 'create_article' %}" hx-target="#monetizable_items" hx-swap="outerHTML">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_content" class="form-label">Enter Article Below</label>
                <textarea class="form-control rounded-4" name="content" id="id_content" rows="10"></textarea>
            </div>
            <button type="submit" class="btn btn-primary ms-auto d-block">Submit</button>
        </form>
    </div>
</div>
```

**Comment by Telroshan** [comment]
Hey, could you by any chance provide some screenshots or logs of what's happening around?
- Could you for example add a console.log with a timestamp on your button's `click` event, and another on say [`htmx:beforeSend`](https://htmx.org/events/#htmx:beforeSend) event on your form? This will let us know how much time is spent between triggering the form's submit and sending the actual htmx request
- Could you provide a screenshot of you browser's dev tools' network tab, which will let us inspect the [timing breakdown](https://developer.chrome.com/docs/devtools/network/reference/?utm_source=devtools#timing-explanation) ?
This way, we could narrow down the issue and figure out if the delay happens when preparing the request or sending it (then we'll be able to narrow it some more depending on the results)

**Comment by Sadeeed** [comment]
Resolved, it was just me being stupid and blaming HTMX for it. Sorry for wasting everyone's time.
