### ISSUE TITLE
[Question] Please confirm the required response headers for different types of redirects.

### ISSUE THREAD

**Issue by RussBaz** [bigskysoftware/htmx#2001]
Hi. Can you confirm which combination of response headers I would need to return from the server for the following cases:

- Redirect without a page reloading:
  - without changing history and URL
  - with pushing a redirect destination as a new history entry and setting the URL to a redirect destination
  - with replacing the current history entry with a redirect destination and setting the URL to a redirect destination
- Redirect with a page reloading:
  - without changing history and URL
  - with pushing a redirect destination as a new history entry and setting the URL to a redirect destination
  - with replacing the current history entry with a redirect destination and setting the URL to a redirect destination

I got myself extremely confused while experimenting with redirects, and I would greatly appreciate some help. My biggest headache is a redirect on successful `post` in the login form, which leads to a page that can also redirect, for example, due to a lack of permissions to view the page by the user. And regardless of what it seems I do, the login form remains cached in history (in Safari).

Thsnk you!

**Comment by Telroshan** [comment]
Hey, let me know if I misunderstood anything there, but I'd say:

- Redirect without a page reloading
  - > without changing history and URL
 

    Simply make a standard HTTP redirect from your server; htmx will follow the redirection and swap in the response of the redirected request, without touching history of the current page's URL
  - > with pushing a redirect destination as a new history entry and setting the URL to a redirect destination
  
    Standard HTTP redirect too + use the [`hx-push-url` attribute](https://htmx.org/attributes/hx-push-url/) (so defined by your client in the HTML), or send the [`HX-Push-Url` header](https://htmx.org/headers/hx-push-url/) from your server (so from the last endpoint accessed, i.e. the one you redirected your client to)

  - > with replacing the current history entry with a redirect destination and setting the URL to a redirect destination
  
    Standard HTTP redirect too + use the [`hx-replace-url` attribute](https://htmx.org/attributes/hx-replace-url/) or the [`HX-Replace-Url` header](https://htmx.org/headers/hx-replace-url/), that work just the same as hx-push-url except they replace the current history entry instead of pushing a new one

- Redirect with a page reloading:
  - > without changing history and URL
     
    Standard HTTP redirect too + send the [`HX-Refresh` header](https://htmx.org/reference/#response_headers) set to `true`. So htmx will follow the redirection, swap the response of the redirected request, then this header will make it reload the current page. No history or URL change

  - > with pushing a redirect destination as a new history entry and setting the URL to a redirect destination
    
    Here you can send the [`HX-Redirect` header](https://htmx.org/reference/#response_headers) from your server. This will make htmx change to the page to the specified location, acting as a standard navigation as if you clicked on a link for example. This will load a new page, that will natively be a new history entry on its own in your browser

  - > with replacing the current history entry with a redirect destination and setting the URL to a redirect destination

    Standard HTTP redirect as the others above + the [`hx-replace-url` attribute](https://htmx.org/attributes/hx-replace-url/) or the [`HX-Replace-Url` header](https://htmx.org/headers/hx-replace-url/) + send the [`HX-Refresh` header](https://htmx.org/reference/#response_headers) set to `true`. So htmx will follow the redirection, swap the response of the redirected request, update the URL of the current page and replace the history entry, then trigger a page reload

Some of these are a little contrived to be honest, for ex I don't see why you would ever use that last one instead of simply redirecting your client, but that's how you could do it!

Hope it helps!

**Comment by RussBaz** [comment]
Thank you for your response! It clarified few things to me that I personally misunderstood. One more thing, though. Can you clarify the intended use case for the `HX-Location` response header?

**Comment by Telroshan** [comment]
I never use this one so don't necessarily take my word for it, but from what I understand of [`HX-Location`](https://htmx.org/headers/hx-location/):
> it will act like following a [hx-boost link](https://htmx.org/attributes/hx-boost/)

>HX-Location: /test
 Which would push the client to test as if the user had clicked on \<a href="/test" hx-boost="true">

So it seems you use it to trigger some client-side action after the current request has ended, i.e. making a second request after the first one has ended. So it looks like a redirection for the user, but is actually really a second request: this redirection happens in a second phase.

I don't have an example usage that comes to mind, especially when this one implies making a whole new request right after, instead of doing everything through the first one. I personnally use the [HX-Trigger](https://htmx.org/headers/hx-trigger/) header whenever I want to trigger some client side logic from the server's response

**Comment by RussBaz** [comment]
Thanks again! I believe this has answered all my current questions. 👍 I'm going to close the issue now.
