### ISSUE TITLE
Using `hx-push-url` and navigating back causes memory leaks

### ISSUE THREAD

**Issue by pbouzakis** [bigskysoftware/htmx#2031]
I noticed an issue where using `hx-push-url` and navigating back in history was causing event handlers attached to the document body to be called multiple times (for each pushState).

Here's a codepen that showcases the issue w/ step to reproduce the issue
https://codepen.io/Paul-Bouzakis/pen/mdvLRjy

I know that htmx has a popstate event handler that leverages a built in cache, so most likely the issue is related to this code, as I can't reproduce using pushState directly.

**Comment by croxton** [comment]
On history restore htmx will process any `<script>`s that it finds inside the history element content that it retrieves from the history cache (in localStorage). So your event listener will get added multiple times, because the `<script>` is in the cache. To prevent this you can define a history element (with the `hx-history-elt` attribute) and put your `<script>` _outside_ of it:
https://codepen.io/croxton/pen/abXGXJZ

**Comment by pbouzakis** [comment]
Great, let me give this a shot.
