### ISSUE TITLE
Out-of-order post data

### ISSUE THREAD

**Issue by sippeangelo** [bigskysoftware/htmx#22]
Since checkboxes don't send a value when unchecked, a common pattern when dealing with them in forms is to hide a sentinel value before it like so, and then always pick the last value given in the post body as the actual value of the field (PHP does this by default).

```html
<input type="hidden" name="check" value="false">
<input type="checkbox" name="check" value="true">
```

However, when adding `hx-post` to the element, the resulting post data seems to end up holding the values in opposite order:

```json
{ "check": [ true, false ] }
```

**Comment by chg20** [comment]
Where are you putting the hx-post?  On the input itself or on the form?

**Comment by sippeangelo** [comment]
> Where are you putting the hx-post? On the input itself or on the form?

On the input.

**Comment by chg20** [comment]
Ah, OK, so that's the problem: an element is going to include its own value first, *then* the value of inputs in the enclosing form.

One option would be to wrap the two elements in a div and put the hx-post on that, as well as a hx-trigger="changed" attribute.  Then the entire form would be included in the correct order.

**Comment by chg20** [comment]
Thinking more on this, I think if the element is included in a form, we should respect the order within the form.  This wasn't a hard change.
