### ISSUE TITLE
purpose use

### ISSUE THREAD

**Issue by needhelpfulanswers-spectrumchat** [bigskysoftware/htmx#252]
q&a: had a few basic questions + clarifications 

1. whats main purpose of this? is it ideally meant to replace html?
2. whats practical use of this currently? or is it just demo?
3. does this solve the porblem of being able to read css + html ? if 99% of ppl are using regular html + css, then if anyone learned this instead of css html, then wont they not be able to read regular css html ?
4. for the 99% of ppl on the web in world that knows nothing about css html, what are the requiremnts / prerequites to learn this thing? i assume there's no beginner guide youtubes etc for many of these things ppl make

mainly intersted in practical use if 99% of ppl that do know how to read css + html are using regular css + html and not this (w/e this htmx thing is)

please show answers in way that any 4 year old would understand

**Comment by benpate** [comment]
The [htmx website](htmx.org) is pretty self-explanatory -- " htmx adds [AJAX](https://htmx.org/docs#ajax), [CSS Transitions](https://htmx.org/docs#css_transitions), [WebSockets](https://htmx.org/docs#websockets) and [Server Sent Events](https://htmx.org/docs#sse) directly into HTML, using attributes..." instead of using Javascript.  So, htmx does not replace HTML.  It is a series of extensions to HTML that make it easier to do AJAX calls on every element -- not just `<a>` and `<form>` elements.  If you understand HTML+CSS, then you already understand htmx -- you now just have a few extra abilities to work with.

htmx is still pretty new (just hit v1.0) so most applications that use it are still works in progress.  I believe the [Sprig plugin for Craft CMS](https://github.com/putyourlightson/craft-sprig) is a good example of production code that uses htmx.

This does not "solve the problem of being able to read css + html" -- this solves the problem of squeezing UI components into Javascript + JSON, then trying to render it as HTML via huge Javascript libraries.  Instead, your server renders HTML and your clients' browsers load and display that.

There are a number of demos, docs, and examples on the [htmx website](htmx.org).  I wouldn't say it's for beginners who don't know HTML or CSS.  You should probably understand those basics first.  However, the learning curve for htmx should be much easier than client-side Javascript frameworks (Angular, React, Vue) because you don't *also* have to know Javascript to use htmx.

I'm teaching htmx to an 11-year-old, if that helps.  But, I doubt it could be explained to a 4-year-old, because they lack the necessary prerequisites of understanding web browsers, HTML, etc.  You should wait until they're at least 5 or 6, and are able to type before you try to teach htmx to children. 😅

I hope this is helpful.  By the way, there's now an [HTMX tag on Stack Overflow](https://stackoverflow.com/questions/tagged/htmx).  Q&A discussions would probably be better on that forum :)

**Comment by 1cg** [comment]
Great answer, thanks @benpate.

Agree this is probably better a StackOverflow question.
