### ISSUE TITLE
Newly Cloned Repo fails the Test command

### ISSUE THREAD

**Issue by sameer-dudeja** [bigskysoftware/htmx#2656]
I recently cloned the HTMX repo and ran the `npm run test` command 
To my surprise without making any changes it failed for 3 tests, I am new to htmx and might be missing something  but in a layman's point of view all tests should pass in the most ideal sense or the test should be modified
I am attaching the screenshot of the failed tests,
![image](https://github.com/bigskysoftware/htmx/assets/16884060/93e07577-6911-47ee-bbac-e8da2bba3e04)

**Comment by kaiji123** [comment]
I have a similar issue when running test , although I just have 2 failed test cases. Below is the screenshot.
![image](https://github.com/user-attachments/assets/a41c4f3f-4bc7-426c-be31-1aa654aa06fc)
It seems that issue comes from security.js file from test\core and www\static\test\core with the error being exceeding Timeout of 4000ms.

In this part of code 
`  it('can make egress cross site requests when htmx.config.selfRequestsOnly is disabled', function(done) {
    this.timeout(4000)
    htmx.config.selfRequestsOnly = false
    // should trigger send error, rather than reject
    var listener = htmx.on('htmx:sendError', function() {
      htmx.config.selfRequestsOnly = true
      htmx.off('htmx:sendError', listener)
      done()
    })
    this.server.restore() // use real xhrs
    // will 404, but should respond
    var btn = make('<button hx-get="https://hypermedia.systems/www/test">Initial</button>')
    btn.click()
  })`
  
  I tried increasing timeout to 12000
` this.timeout(12000)`

and surprisingly the failed case didn't show up anymore.

![image](https://github.com/user-attachments/assets/d70fc432-8938-4a2b-bc23-df79e328c8e8)

**Comment by Telroshan** [comment]
Hey, indeed those tests make requests to external URLs and it's unfortunately common to have timeout issues with those...
As it's going to depend on your internet connection for that request, that's probably why increasing the timeout worked for you here.
We need these tests to ensure `selfRequestsOnly` works as expected, so if you have any idea how to solve that timeout problem (without simply increasing the timeout value in this case), PRs are welcome!

**Comment by kaiji123** [comment]
> Hey, indeed those tests make requests to external URLs and it's unfortunately common to have timeout issues with those... As it's going to depend on your internet connection for that request, that's probably why increasing the timeout worked for you here. We need these tests to ensure `selfRequestsOnly` works as expected, so if you have any idea how to solve that timeout problem (without simply increasing the timeout value in this case), PRs are welcome!

Do you think that mocking a fakeserver response would resolve the timeout issue?

**Comment by 1cg** [comment]
closing as it is mostly working except for the external URL ND aspect (which will fix after the second run)
