### ISSUE TITLE
Broken `hx-boost`/`hx-get` swap behavior

### ISSUE THREAD

**Issue by nbonfils** [bigskysoftware/htmx#2685]
In the following setup I have two pages linking to each other with <a> tags. I have the `hx-boost="true"` set on body and when navigating from *Edit* to *Home*, it works fine, but from *Home* to *Edit*, the swap does not finish and I end up with a blank page.
I suspect it's the swapping that's not working, because I tried to change my anchor tags to use the `hx-get` attribute instead of `href` and the result was the same, a blank *edit* page.

Let's illustrate with some snippets, here are my two pages:

```html
<!-- Home -->
!DOCTYPE html>
<html lang="en">
  <head>
    <!-- ... -->
  </head>
  <body hx-boost="true">
    <h1>Welcome to My Website</h1>
    <div>
      <button hx-get="/logout" hx-swap="outerHTML">Logout</button>
    </div>
    <br>
    <main hx-get="/" hx-select="main" hx-swap="outerHTML" hx-trigger="loginEvent from:body">
      <a href="/edit">Edit</a>
    </main>
  </body>
</html>
```

```html
<!-- Edit -->
!DOCTYPE html>
<html lang="en">
  <head>
    <!-- ... -->
  </head>
  <body hx-boost="true">
    <h1>Edit</h1>
    <a href="/">Home</a>
  </body>
</html>
```

If I am on *Edit* and click on the `Home` link, it works find, the body tag was swapped correctly and I end up with this:

```html
<!-- Home -->
!DOCTYPE html>
<html lang="en">
  <head>
    <!-- ... -->
  </head>
  <body hx-boost="true">
    <h1>Welcome to My Website</h1>
    <div>
      <button hx-get="/logout" hx-swap="outerHTML">Logout</button>
    </div>
    <br>
    <main hx-get="/" hx-select="main" hx-swap="outerHTML" hx-trigger="loginEvent from:body">
      <a href="/edit">Edit</a>
    </main>
  </body>
</html>
```

On the other end, if from *Home* I click on the `Edit` link, then I end up with a blank page:

```html
<!-- Edit -->
!DOCTYPE html>
<html lang="en">
  <head>
    <!-- ... -->
  </head>
  <body hx-boost="true"></body>
</html>
```

I can see the request with the proper response in the dev console:

![1719692788](https://github.com/bigskysoftware/htmx/assets/14347927/644a9243-60ae-474b-aaf2-ff60ff769200)

Doing `ctrl+u` also shows the following:

```html
<h1>Edit</h1>
<a href="/">Home</a>
```

And after losing a few hair trying different setup with `hx-get` or using the `htmx.config.useTemplateFragments` config, etc... And search around the web, I discovered the `htmx.logAll()` function to try and see what is going on. So then I can see the `beforeSwap` event that sees the correct server response:

![1719693251](https://github.com/bigskysoftware/htmx/assets/14347927/48343b9c-e283-4df4-8b58-bb973eff2d73)

And the `afterSwap` looks quite funky with the empty `<body>` but the `xhr.response` containing the proper html:

![1719693325](https://github.com/bigskysoftware/htmx/assets/14347927/587eb6fd-c5a1-4b12-92d9-fa9103466c9c)

I happy to provide more info if I can, but this seems like an issue that's above my ability to debug this further...

**Comment by nbonfils** [comment]
Continuing with my experiments, I realized that taking the `<a href="/edit">Edit</a>` out of the `<main>` tag then works. So any elements with `hx-get` inside `<main>` seems to not be able to swap properly...
I haven't read anywhere in the documentation that nesting tags with htmx attribute was problematic, I am not sure if this is "expected" behavior.

**Comment by Telroshan** [comment]
Hello, I'm not familiar with `hx-boost` at all but a few ideas:

You mentioned moving the link out of main works. From what I see, your `main` tag defines a few attributes that are inherited by its children, thus the link when it's inside, which _could_ be the cause of the issue you're having:
- [`hx-select`](https://htmx.org/attributes/hx-select/) _probably_ turns your request's response into "nothing" as it doesn't contain a `main` tag to select inside
- [`hx-swap`](https://htmx.org/attributes/hx-swap/) is also inherited, _probably_ turning your initially `innerHTML` swap (the [default](https://github.com/bigskysoftware/htmx/blob/master/src/htmx.js#L3563) when boosting) into a `outerHTML` swap
- Since you don't define a `hx-target`, the body is [used as a fallback](https://github.com/bigskysoftware/htmx/blob/master/src/htmx.js#L1352-L1353), thus maybe results in that blank page?
So, what I imagine is happening here, is that `hx-select` selects nothing as the request's response doesn't contain a `main` tag, `hx-swap="outerHTML"` instructs to replace the target with "nothing", and that target being the body, it's like replacing the body's outerHTML so the body itself, with "nothing".

Hope this helps!

**Comment by nbonfils** [comment]
Yes, I actually just figured it out too! So it was indeed the `hx-select="main"` that was inherited and since there is no `<main>` tag on the *Edit* page, the page ended up blank.

To address this I needed to wrap everything inside `<main>` with a `<div hx-select="unset">` tag.

A solution to my problem might look like this:
```html
<!-- Home -->
!DOCTYPE html>
<html lang="en">
  <head>
    <!-- ... -->
  </head>
  <body hx-boost="true">
    <h1>Welcome to My Website</h1>
    <div>
      <button hx-get="/logout" hx-swap="outerHTML">Logout</button>
    </div>
    <br>
    <main hx-get="/" hx-select="main" hx-swap="outerHTML" hx-trigger="loginEvent from:body">
      <div hx-select="unset">
        <a href="/edit">Edit</a>
        <!-- some more main content unaffected by hx-select -->
      </div>
    </main>
  </body>
</html>
```

Thank you for your help too!
