### ISSUE TITLE
hx-trigger="click from:.class" are not updated

### ISSUE THREAD

**Issue by ChrisJefferson** [bigskysoftware/htmx#2689]
Given a div like:

```
<div id="container" hx-get="/target" hx-trigger="click from:.literal" class="thebox">
...
</div>
```

This works fine (finding all things which match `.literal`), but if I load a new thing via htmx, it is not scanned. Further, even if I run `htmx.process(document.documentElement)`, to (I believe) force a full scan, the things with class `literal` still aren't found, I think because htmx notices the `div` hasn't changed, so it doesn't rescan it.

If I "poke" the div, by giving it a new class (for example), then run `htmx.process(document.documentElement)`, then it will finally find new items with the `.literal` class.

While my actual problem is a htmx problem, I load a div, which contains an svg, where lots of items have the ".literal" class, and they don't become clickable.

I've tried to write a minimal awful HTML+Javascript example to show the problem (attached)

It has 3 buttons:

The first adds the class  'literal' to the text 'hello world', but it doesn't become clickable.

The second runs 'htmx.process', but that doesn't fix it

The third changes the div with the 'hx-get', attaching a new 'class' to it. This still doesn't fix it.

However, now reclicking on the second button now correctly rescans, and we can finally click on 'hello world', and get a result.

[example.zip](https://github.com/user-attachments/files/16070041/example.zip)

I feel like there are two(ish) issues here (but I might be misunderstanding my problem)

1) When HTMX loads something, it should maybe try reapplying any triggers with a 'from', to see if they apply to the new content.

2) htmx.process shouldn't try to cleverly skip things with a 'hx-trigger' with 'from' (if that's what it's doing).

**Comment by ChrisJefferson** [comment]
As a quick hacky fix, I've added a boolean to `process`, (and `initNode`, which process calls), which lets me treat all nodes as 'changed' (treat them as if their cache doesn't match), which lets me fully refresh my page.

This feels a bit like a sledge-hammer (and is basically admitting the cache can get broken), so I'm not sure if you'd want a PR for that, unless this 'bug' should be promoted to 'feature'.

**Comment by Telroshan** [comment]
Hey, the way that `hx-trigger` works is that, when initializing the node that declares this attribute, htmx will bind listeners to all elements matching that selector.
So when your `hx-trigger="click from .literal"` enters the DOM, htmx will find all `.literal` elements and bind listeners to them. Then, htmx cannot know (without adding much complexity I mean) automatically that you added another `.literal` that a new listener should be bound to, as the `hx-trigger` element itself didn't receive any event, nor was it updated.

Now, the gotcha with `htmx.process` is that, to avoid reprocessing an already-processed node, htmx computes a hash using the element's attributes and if that hash didn't change, ignores the processing request.
https://github.com/bigskysoftware/htmx/blob/f4f448db0a413e403d3c7f627d9e6d2b356bf0d8/src/htmx.js#L2791-L2792
This is of course an issue in your case, as the `hx-trigger` element itself didn't change.

While I see the interest of adding a boolean to force processing here (and ignore that hash comparison thing), given your situation and your HTML (root element containing `.literal` ones), what do you think of using a single click listener on your root element itself, and using a conditional to filter the source element ? Instead of your current setup where you would bind a click listener on each and every `.literal` element + would have to deal with inserted nodes
Something like
```html
<div id="container" hx-get="/target" hx-trigger="click[event.target.matches('.literal')]" class="thebox">
```

You can try it on [this JSFiddle](https://jsfiddle.net/neby3rqx/), see how clicking on the header doesn't fire any request at first, then clicking on the button to add the class and clicking on the header again now correctly fires the request, without requiring any extra `htmx.process` call

**Comment by ChrisJefferson** [comment]
Thanks, that's much better. I was attached at all to what I was doing, I just didn't really want to either (a) fill my svgs with hx tags (as I use them for other things), or use a bonus evil javascript function to fill them all in.

Longer term, I do wonder if the `from:` option should have some warnings attached to it -- it seems fairly difficult to use it correctly when matching a class.

**Comment by Telroshan** [comment]
I'm not gonna lie ; I always use hx-trigger's `from` keyword with `from:body`, mostly for headers sent from the server (to trigger some refreshes along a response), or for say `mousedown` events that should close a popup / tab or things like that in the foreground, to get a behavior of "any click outside the element should close it" (`mousedown[isClickOutside()] from:body` for ex)

I agree, `from`'s documentation should probably mention that it'll be resolved to the elements matching the selector _at the time_ the element is inserted into the DOM and won't be evaluated again later on, thus new elements wouldn't trigger it.
Feel free to open PR to enhance the documentation if you feel like it! 😃
