### ISSUE TITLE
hx-swap-oob not working as expected

### ISSUE THREAD

**Issue by anuj9196** [bigskysoftware/htmx#2742]
```html
<script src="https://unpkg.com/htmx.org@2.0.1" integrity="sha384-QWGpdj554B4ETpJJC9z+ZHJcA/i59TyjxEPXiiUgN2WmTyV5OEZWCD6gQhgkdpB/" crossorigin="anonymous"></script>
<script src="https://unpkg.com/htmx-ext-response-targets@2.0.0/response-targets.js"></script>
<script src="https://unpkg.com/htmx-ext-ws@2.0.0/ws.js"></script>
```

In parent file, I have the following form code

```html
<form x-ref="authForm" role="form" hx-post hx-target-error="#authentication_password">
  {% csrf_token %}

  {% include "style-guide/components/input.html" with form=form name="email" label="Email" placeholder="Email" %}

  <div id="password1"></div>

  <div class="text-center">
    <button type="submit" class="mt-4 btn bg-gradient-primary w-100" :disabled="submitted">
      Authenticate
      <i x-show="submitted" class="fa-solid fa-spinner fa-spin ms-2"></i>
    </button>
  </div>
</form>
```

and the response file is
```html
<div id="password1" hx-swap-oob="true">
  {% include 'style-guide/components/otp.html' with form=form name="password" %}

  <a href="#" class="text-secondary font-weight-bold no-otp">Don't have OTP?</a>
</div>
```

I want the response content to be replaced with `<div id="password1"></div>` in the parent. But instead, it is replacing the entire `form` innerHTML.

Removing `hx-swap-oob="true"` at least renders the response, but with this, it does not render anything and the component goes blank

This is the main screen
<img width="546" alt="Screenshot 2024-07-19 at 8 16 07 AM" src="https://github.com/user-attachments/assets/4f3d68f4-d533-4a10-8efe-a875e1b1a089">

This is after the response with `hx-swap-oob="true"`
<img width="857" alt="Screenshot 2024-07-19 at 8 15 20 AM" src="https://github.com/user-attachments/assets/a2b8d987-94c5-4bce-8d01-cde1478af6ce">

This is after the response without `hx-swap-oob="true"`
<img width="477" alt="Screenshot 2024-07-19 at 8 21 57 AM" src="https://github.com/user-attachments/assets/3a91e7da-1fba-4e9d-a5c5-98ae32b4c59f">

Note in the last screenshot the submit button has also removed replacing all elements of the form.

**Comment by Telroshan** [comment]
I suppose here that it's your form's `hx-post` request that returns the password group snippet.

You can indeed use `hx-swap-oob` to swap content out of bands, i.e. outside your initial target and basically anywhere you want in the page. But that doesn't prevent the default swapping feature from happening.

What I suspect is happening here, is that since your form doesn't specify `hx-target`, the form itself is the target as the default value of `hx-target` is the element itself. Since you don't specify `hx-swap` either, the default swap style `innerHTML` is applied.

So, it could be that your request replaces the entire content of your form with nothing (as your response only contains an element to swap out of bands, thus the remaining HTML is just an empty text, that replaces your form's `innerHTML`).
Could you try maybe with `hx-swap="none"` on your form ?

**Comment by anuj9196** [comment]
Adding `hx-swap="none"` worked for me. Thanks!
