### ISSUE TITLE
Example when searching a form (multiple fields)

### ISSUE THREAD

**Issue by tacman** [bigskysoftware/htmx#2840]
The active search example is great for searching just a single field.

I'd like to add a second field, a checkbox to only search active users.  

since I need _both_ fields to be present in the search, I don't think I should add the hx-get in in the input element (which works, but it gets _either_ q or active_only).

So I moved it to the a form, but that didn't work.  Any suggestions?  Thanks.

```html
<form
        hx-get="/search"
        hx-target="#search-results"
        hx-trigger="load"
        hx-indicator=".htmx-indicator"
    >

    <input class="form-control"
           hx-trigger="load, input changed delay:400ms, search"
           type="search"
           name="q" placeholder="Begin Typing To Search Users..." />
    <input name="active_only"
           hx-trigger="input changed delay:100ms, search"
           type="checkbox"/>Active Only
</form>
```

**Comment by Telroshan** [comment]
Hey, the `hx-trigger` specifications have to go on the element that defines the `hx-get` in this case.
You can use its [`from` modifier](https://htmx.org/attributes/hx-trigger/) here, such as 
See an example on [this JSFiddle](https://jsfiddle.net/1y09rf6g/) _(open the network tab to inspect the requests being fired, as of course nothing gets swapped in since the endpoint doesn't exist there)_

Essentially this:
```html
<form hx-get="/search" hx-target="#search-results"
  hx-trigger="load, input changed delay:400ms from:find input[type='search'], input delay:100ms from:find input[type='checkbox']">
  <input class="form-control" type="search" name="q" placeholder="Begin Typing To Search Users..." />
  <input name="active_only" type="checkbox" />Active Only
</form>
```

If you're ok to use the same delay for both inputs, then you can greatly simplify the above trigger:
```
hx-trigger="load, input changed delay:400ms from:find input"
```

Hope this helps!

**Comment by tacman** [comment]
Awesome, thanks!
