### ISSUE TITLE
hx-get sends empty query param on date picker 'clear'

### ISSUE THREAD

**Issue by cptwunderlich** [bigskysoftware/htmx#2864]
The following behavior seems like a bug to me:

I have a date control, like so:
`<input type="date" name="date" hx-get="foo" hx-target="#output">`

When I select a date, a request to `/foo?date=2024-09-03` is sent. Great.
My Browser's date picker has a "clear" button. When I press that, a request is issued to `/foo?date=`.
Is this behavior expected? 

The docs state that 
> By default hx-get does not include any parameters. 
(https://htmx.org/attributes/hx-get/)

Which is clearly not correct and disagrees with https://htmx.org/docs/#parameters
> By default, an element that causes a request will include its value if it has one. 

So in this case, the element has a value, but it is empty. Should this be included? (IMHO: no).

Do I need to resort to `htmx:configRequest` to get rid of this? Unfortunately, the server I use, does not accept these empty params.

Here is a hacked together reproducer, using flask:
https://gist.github.com/cptwunderlich/162a45c21243e31ab92dcb34e00b05fd

**Comment by Telroshan** [comment]
Hey, indeed the docs are a bit confusing to me too.

[hx-get](https://htmx.org/attributes/hx-get/) doc says
> By default hx-get does not include any parameters. You can use the [hx-params](https://htmx.org/attributes/hx-params/) attribute to change this

The first strange thing to me is that this doc mentions `hx-params` but that one is used to filter **out** values, as after all, its doc mentions:
> \* - Include all parameters (default)

So I would have instead thought of [`hx-include`](https://htmx.org/attributes/hx-include/) that is used precisely for this matter:
> The hx-include attribute allows you to include additional element values in an AJAX request

Worse, the `hx-params` doc has this example:
>   ```<div hx-get="/example" hx-params="*">Get Some HTML, Including Params</div>```
This div will include all the parameters that a POST would, but they will be URL encoded and included in the URL, as per usual with a GET.

But that very example [doesn't seem to work](https://jsfiddle.net/ezvryp3q/), and on the other hand, replacing precisely the `hx-params="*"` with a `hx-include="*"`, or a `hx-include="this"` to only include this element's children, works as you would expect.



I was thinking the `hx-get` sentence ("By default hx-get does not include any parameters") could be related to non-GET requests including their closest form's values as stated in [the docs](https://htmx.org/docs/#parameters):
> Additionally, if the element causes a non-GET request, the values of all the inputs of the nearest enclosing form will be included.

This behavior has been in the lib for at least 3 years if I recall correctly, though this looks like a convoluted way to refer to that? So I'm unsure it's about that.


> So in this case, the element has a value, but it is empty. Should this be included? (IMHO: no).

Again, I think it's probably poorly formulated in the docs, but here's the thing:
- As you can observe on [this JSFiddle](https://jsfiddle.net/14vo5t8e/), a default form (no htmx involved) will include the date input, even when it hasn't a value (I get `?test=` in the URL). As htmx strives to mirror the behavior of native forms and elements as much as possible, this looks like the correct & expected behavior to me
- I would guess that the intention in those docs are to say that if it's an input element i.e. that can declare a `name`/`value` pair, then it will be itself included in the request. So the `if it has one` is probably a `if it's a value-based element` rather than literaly "if its value is set"

Another example [on this JSFiddle](https://jsfiddle.net/14vo5t8e/1/), a checkbox will by default not be sent at all along the request if it's unchecked in a standard form, and is only sent along if it's ticked. htmx reproduces that behavior too.

So, to sum all this up ; I think the behaviors you're seeing all are expected, and it's instead the docs that are either obsolete, or poorly formulated.

Btw, PRs are always welcome to improve the documentation!

> Do I need to resort to htmx:configRequest

If you really can't make your server process empty parameters (why though?), then y a `htmx:configRequest` handler is probably your best option

Hope this helps

**Comment by cptwunderlich** [comment]
> If you really can't make your server process empty parameters (why though?)

I found a workaround. Yeah, I'm not sure how other servers handle this. I'm using [Tapir](https://tapir.softwaremill.com/en/latest/), which is not actually a server, but a library for declarative rest endpoints.

> Btw, PRs are always welcome to improve the documentation!

I'll consider it :) This week I'm swamped, but maybe later.
