### ISSUE TITLE
oob-swap fails when returned node has hx-swap-oob="true"

### ISSUE THREAD

**Issue by belowm** [bigskysoftware/htmx#2900]
When a node is oob-swapped with a node that also has `hx-swap-oob` set to `true`, the node is not swapped, and the previous node is removed from the page.

Consider this test case, which passes:
```javascript
  it('handles oob swap', function() {
    this.server.respondWith('GET', '/test', `<span id="oob">bar</span>`)

    var page = make(`
      <div hx-target="this" hx-boost="true">
        <span id="oob" hx-swap-oob="true">foo</span>
        <a id="link" href="/test">page1</a>
      </div>
    `)

    byId('link').click()
    this.server.respond()
    should.not.equal(byId('oob'), null)
    byId('oob').innerHTML.should.equal('bar')
  })   
```

where this fails:
```javascript
  it('handles oob swap where swapped node has hx-swap-oob="true"', function() {
    this.server.respondWith('GET', '/test', `<span id="oob" hx-swap-oob="true">bar</span>`); // note the hx-swap-oob attribute here

    var page = make(`
      <div hx-target="this" hx-boost="true">
        <span id="oob" hx-swap-oob="true">foo</span>
        <a id="link" href="/test">page1</a>
      </div>
    `)

    byId('link').click()
    this.server.respond()
    should.not.equal(byId('oob'), null)
    byId('oob').innerHTML.should.equal('bar')
  })
```

**Comment by belowm** [comment]
This might be about using `hx-boost` in conjunction with `hx-swap-oob`.

**Comment by MichaelWest22** [comment]
I don't know if these tests make sense as you should not be using oob swap with a boosted link like this.  In the first test there is no oob swap involved as hx-swap-oob is only valid in a htmx partial response but you have put the tag into the initial page contents.  So for this test it is just testing a boosted link with no oob swap

For the second test you have the same swap attribute on the page which does nothing and you have it performing a normal http link request but with boost applied again which will swap in the whole response into the body.  But the response just has a oob swap data and no other page content which may work and swap in the oob content but it will do this swap in first.  After it has done the oob swap it should then take the remaining content which is blank in this case once you remove the oob tag and replace the body with this remaining response.  So we would expect this to remove all content from the page.

**Comment by belowm** [comment]
Thanks, this nakes sense, I think I over-simplified the scenario in my attempt to narrow down a more complex setup I'm having this issue with. I'll provide a new test.

> hx-swap-oob is only valid in a htmx partial response 
Can you please elaborate more on the limitations of oob swap in conjunction with with hx-boost? Is this a valid combination at all?

>  In the first test there is no oob swap involved [...]
Please note that both tests are exactly the same, except for `hx-oob-swap="true"` being present on the response.

**Comment by MichaelWest22** [comment]
In the first test you put a hx-oob-stop attribute on the page.  This is ignored as this tag is only active in a response from a server to a hx request where there is oob content checking before the response is swaped into the page.

Links with no hx attributes but under a hx-boost are meant to act as full links like normal except they use boosting which replaces the body of the page with the body of the response via Ajax and do not update the page head and head scripts etc.  Faster than a full page load because of this.  But boosting only replaces the whole body content of the page.

  Oob swaps are designed to be used only with partial hx swap changes.  The idea is you have a request from say a button that swaps in the main central div on your page with new content. but you also need to update a notification in the top bar of the page as well so when you return the central page content you also return a bit of oob update data to notification div.  

You can't replace the whole page and part of the page at the same time logically so these two features are not usable together.  Use boosted links to change the whole page to a new state like you would do in an old Multi page application.  Use oob swaps to do what a SPA style update small parts of the UI would do.

**Comment by belowm** [comment]
Thank you for taking the time. I think I need to add a bit of context and clarification where I'm coming from.

I have a traditional multi-page application. Generally, I don't want to render my server side HTML with too much of HTMX in mind: 
- I ideally don't want to add htmx attributes to all of my `a` nodes, because the URL is already given in `href` 
- same for forms (HTTP verb and URL is already present in `method` respective `action`)

I'd like my web app to still work without HTMX, which I think is great for screen readers, search engine crawlers and devices where JavaScript is not supported. As I understand, this is the situation the `hx-boost` feature was designed for.

So for now, the server always responds with a full HTML page. (I'm aware that this leaves room for optimization, which I want to tackle later by hinting the server what portion of the page needs to be rendered using a HTTP header for the htmx requests). 

So I started off adding `htmx-boost="true"` to progressive-enhance my traditional multipage app.  This works well. Next, I wanted to narrow down the content that is swapped. So I added `hx-select` and `hx-target` to the main navigation, because those links typically only change a specific part of the page. This basically works well, except that I have a node that contains notifications (messages) that exists outside of the element I specified with `hx-select` / `hx-target`. So I added `hx-swap-oob="true"` so tell HTMX to always update the messages element. 

This leaves me with something like this. 
```html
<html>
  <head>
    <script src="https://unpkg.com/htmx.org@2.0.2"></script>
  </head>
  <body hx-boost="true">

  <!-- links in nav shall swap the main element -->
  <nav hx-select="main" hx-target="main">
    <!-- those links work just fine.
         main and messages are updated -->
    <a href="page1.html">page1<a>
  </nav>

  <!-- this shall always be updated -->
  <section id="messages" hx-swap-oob="true">
    messages go here
  </section>
  
  <!-- links in the main section should update the whole page -->
  <main>
    <p>content goes here</p>
    <!-- this does not work: content note is swapped, but messages note disappears completely -->
    <a href="page1.html">A link in the content section.</a>
  </main>
</body>
```
(Please save the above as `page1.html` to reproduce the issue).

Because all of my pages are based on this template, `hx-swap-oob` is always present on the `messages` node - no matter if the page was requested "traditionally" upon first page load, or subsequently by htmx.

And this leads me to the problem I tried to isolate above. Links inside `nav` work just fine, whereas links inside `main` remove the messages section from the page. 
Maybe I have some wrong assumptions about these concepts?

**Comment by belowm** [comment]
As a workaround, I just discovered that adding this to the `main` node fixes the issues:

```html 
<main hx-target="main" hx-select="main">
```
This excludes the messages node from the "primary swap" (which is still be updated out of bands).

So if I understand correctly, the issue here is that the messages node is targeted by two swaps at once:
- the "primary swap" that updates the whole body contents
- the oob swap as denoted by `hx-swap-oob="true"`

That would mean that once a node has `hx-swap-oob="true"`, it cannot be updated by any other means (meaning one cannot swap one of its parents).

So I guess this is more a limitation of htmx than a bug?

**Comment by MichaelWest22** [comment]
yeah the limitation is that you can not return hx-swap-oob in content if the target of the main swap is the parent of the element with the id you are oob swapping in.  This is because oob swaps work by swapping in that content first and then removing it from the main response and then it swaps in the remaining response by removing the whole target (including the oob swapped element you just replaced) with the updated response that now does not include the oob swap data.  I don't think this is really intentionally trying to do this but because of how oob swap works this is just what has to happen.  When doing boosted links they target body by default and as you have found this always triggers the issue.  using a more targeted swap via target and select as you have found works around the problem.  It would be possible to make oob swap checking code smarter by getting it to skip doing oob swaps if the main target was 'body' or a more advanced version that checks manually if the target id of the oob swap has the main swap target as a parent and abord the oob swap but this is much more complex and could cause issues so probably not worth it for this edge case you have found.

There is also a setting you could try [hx-preserve="true"](https://htmx.org/attributes/hx-preserve/) which you can set on an element that you always want to keep when replacing the whole page with a boosted link and if this is your oob swapped in content i think it may do what you want.

I think as you get further into replacing and updating your app you will find better patterns to avoid the issues you are having right now.  One solution is to make your backend responses a bit smarter.  To do good progressive upgrade of the page and still support clients that can't use htmx like your trying to do you need to get your server to respond with different content.  htmx sends really useful request headers with each request and you can use these to make your responses much smarter.  if your sever gets HX-Request=true request header you know they have htmx javascript running and htmx made the request.  and if HX-Boosted is set it was a link or form that did a full page boost probably.  So you can read these headers on your backend and based on that return either the full page template ( if HX-Request not set OR HX-Boosted = true) with no hx-swap-oob or you just return the cut down template with you main content and any updated oob swaps for other elements.  if all your links and updates follow this pattern then you get much of the speed and power of htmx but it will work without it as well.  However more advanced htmx behavior than just faster partial updates will be harder to implement with full no javascript backwards compatibility.

**Comment by belowm** [comment]
Thanks for the clarification.
