### ISSUE TITLE
Inherit hx-vals for swapped in items

### ISSUE THREAD

**Issue by Xenira** [bigskysoftware/htmx#2906]
I have a infinite scrolling list with some hx-vals to set global parameters. The trigger for loading the next page just replaces the `offset` value.

On initial load the first trigger works without problems and includes all the correct values `/api/search?limit=50&some-param=foo&offset=50`.

All subsequent requests from the swapped in triggers include none of the inherited values and just calls `/api/search?offset=100`.

I also tried to inherit explicitly using `hx-inherit` but the behaviour stayed the same.
I am using htmx version `2.0.2`

Any hints would be appreciated.

```html
<ol id="foo"
    hx-vals="{"limit":50,"some-param":"foo","offset":0}"
>
    <div
        hx-val="{"offset": 50 }"
        hx-get="/api/v1/search"
        hx-target="#foo"
        hx-trigger="intersect once"
        hx-swap="beforeend" class="">
    </div>
    <li>some entry</li>
    [...]
</ol>
```
(quotes in hx-vals replaced for readability. Its valid json and works fine on first request)

**Comment by MichaelWest22** [comment]
Sorry I was unable to reproduce the issue where it excludes the `<ol>` hx-vals.  Tried just reproducing your code snipit you provided and changed hx-val -> hx-vals which was probabaly just a miss type when you uploaded it and also changed hx-vals to use single quote wrappers and it just worked for me.  I would inspect the page content in the browsers dev tools when it is running because you will probably find the layout as it gets swapped into the page may not be what you were expecting and maybe something is not wrapped or placed in the right way in the final page preventing htmx from finding the parent hx-vals somehow.

I also re-wrote it to look like this to test:

```html
<input hidden="true" id="limit" name="limit" value="50" class="fooinput"/>
<input hidden="true" id="some-param" name="some-param" value="foo" class="fooinput"/>
<ol id="foo" ></ol>
    <div
        hx-get="/api/decrement?offset=50"
        hx-target="#foo"
        hx-trigger="intersect once"
		hx-include=".fooinput"
        hx-swap="beforeend" class="">
    </div>
    <li>some entry</li>
</ol>
```
By using hidden inputs placed somewhere on the page you can then reuse them later with hx-include easily and the big advantage of using hidden inputs like this is it is much easier to target these inputs for updates later if required to change their value with htmx requests or JS.  Also using hx-vals to set a single parameter on the current request url can be simplified to just manually putting it at the end of the url directly which I think makes it simpler and easier to understand.

**Comment by Xenira** [comment]
Ohh my god. You are right. Checked so many times, and just noticed that the elements got appended outside of the ol.

Thanks for looking into it and for the suggestion. And sorry for the trouble, was my mistake.

**Comment by MichaelWest22** [comment]
another quick note is that instead of using beforeend swap style and targeting the parent ol I think it is better to start by filling in the first set of 50 list item results and then put the "intersect once" div that fetches the next 50 at the bottom with a id.  this div can then target itself for replacement with outerHTML swap style and each fetch it replaces itself with the response which has another 50 records plus a new version of the intersect once div with offset 50 higher until there are no more records and you skip returning this div.

**Comment by Xenira** [comment]
As the search queries take a little longer to load (depending on data from external systems) I want to fetch one list asynchronously in advance. That way the scrolling experience is smoother.

**Comment by MichaelWest22** [comment]
Then i would just start with the contents equal to just the intersect once fetching div that replaces itself with the first 50 results.  But maybe get the first one to have hx-trigger="load" and have the end div returned by api/v1/search have intersect once.  Also put some content in the div to let the user know it is doing the fetch.
