### ISSUE TITLE
Event htmx:restored doesn't seem to be documented

### ISSUE THREAD

**Issue by scrhartley** [bigskysoftware/htmx#2920]
I've looked for `htmx:restored` in the docs and reference pages on the site and it seems to be missing.
(I was looking for events related to boosting.)

**Comment by MichaelWest22** [comment]
This is not a core part of htmx but is actually from an extension https://github.com/bigskysoftware/htmx-extensions/tree/main/src/restored

see #668

**Comment by scrhartley** [comment]
I am looking in in the htmx [source](https://github.com/bigskysoftware/htmx/blob/master/src/htmx.js) in the master branch:
```js
window.onpopstate = function(event) {
    if (event.state && event.state.htmx) {
      restoreHistory()
      forEach(restoredElts, function(elt) {
        triggerEvent(elt, 'htmx:restored', {
          document: getDocument(),
          triggerEvent
        })
      })
    } else {
      if (originalPopstate) {
        originalPopstate(event)
      }
    }
  }
  ```

**Comment by MichaelWest22** [comment]
Yeah you can read more about what happened in the 668 PR link i posted above.  someone proposed adding a new feature to add a restored trigger type that fires when content is loaded which happens when you push back button and the history is restored.  because adding every new proposed feature directly into htmx is not ideal instead they normally get new features to be added as extensions and if they prove to be really useful then they may get introduced into core htmx later.  So the feature was moved to an extension but I think they may have missed something here as when this extension was created it should not have had to change htmx at all and the extension could have just listened to the existing htmx:historyRestore event for it to trigger the required behaviour only for users that want to run the extension.  Instead 80% of the changes were retained in the core htmx and only the final 20% were moved into the extension.  This is why it is so confusing now with 80% of a feature implemented for people to find but no comment to link to the extension from that code.  

One annoying thing is It may not be easy to now move this feature into htmx by putting back the three lines that were removed when it was turned into an extension as this may then trigger the restored event twice for existing exension users making it kind of a breaking change.  and removing the core htmx changes and updating the extension to use the proper htmx:historyRestore event would also break apps that forget to update the extension to the newer version.

**Comment by scrhartley** [comment]
Thanks, I now understand that this isn't a generally useful event because it only applies to elements with `hx-trigger="restored"`.
For a general event `htmx:historyRestore` should be used.

Closing ticket as a historical artefact that doesn't need further publicity.
