### ISSUE TITLE
HX-Refresh triggers POST in htmx 2.0.2

### ISSUE THREAD

**Issue by oliverbienert** [bigskysoftware/htmx#2941]
Hello,

In a django app, after handling form data from a modal dialog, I return a 204 response together with the HX-Refresh header when required:
```python
            form.save()
            response = HttpResponse(status=204)
            if 'region' in form.changed_data:
                response['HX-Refresh'] = 'true'
            response['HX-Trigger'] = json.dumps({'settingsChanged': True})
            return response
```
This works with htmx 1.9.12. However, after I updated htmx to version 2.0.2 the refresh triggers a POST request which makes my views fail as I allow GET only.
For now, I switched back to version 1.9.12.
My question, however, remains: is this change of behavior intentionally or an error?

Kind regards, Oliver

**Comment by Telroshan** [comment]
Hey, as far as I can tell, what you're observing should have been the behavior from the beginning, when `HX-Refresh` was introduced by commit 67e6fc89e1c93624a52d5b32ed551b1387cef95a

We can see in this commit that the `HX-Trigger` header is processed before `HX-Refresh`, both being processed before the `204` status check, so events are fired before the refresh occurs.
I guess it's likely a timing issue then, whether your browser has the time to fire the associated requests or not before the refresh occurs.

I may be missing something, but I would say this was the expected behavior from the start.

If I may ask, in your situation above, wouldn't simply writing the `HX-Trigger` header in a `else` block do the job ? As it seems you don't want the trigger to happen when requesting a refresh, you might as well not send the trigger header at all when you send the refresh one.

Hope this helps!

**Comment by Telroshan** [comment]
Realizing I maybe read that wrong... 😆 

In case it's the refresh _itself_ that sends a POST request, you might want to check how you landed on the page in the first place. htmx simply calls [`window.location.reload`](https://developer.mozilla.org/en-US/docs/Web/API/Location/reload) and has been calling it from the start so no implementation change occurred on that aspect.

However, and you can try that with a standard form + vanilla JS (thus no htmx involved), if you call `location.reload` on a page that you landed on through a `POST` request (submitting a standard `method="post"` form for example), you will observe that the refresh is also a `POST` request.

If my first comment is totally off the mark and this is what you were describing, then could you check that you properly landed on the page through a `GET` request and not a `POST` one ?

Hope this helps!

**Comment by oliverbienert** [comment]
Hey, thank you for looking into this. I apologize for it was most probably my mistake. The reason was that I accidently had a form within a form by using crispy-forms, so that the form was submitted using a POST while I had a `hx-post` in the outer form which didn't fire.
I extended my python form class to include the `hx-post` attribute and removed the outer form element. Now everything works as expected.
As a side note, I know somehow that a full page refresh is not very htmx-like but is quick enough for now. Someday I would eventually replace it by swapping in updated html fragments triggered by some events like that one above in my previous post.

**Comment by Telroshan** [comment]
> I know somehow that a full page refresh is not very htmx-like 

It's totally ok, and I would even say encouraged, to do full page loads when it makes sense! htmx is not a SPA cult, and if you're going to replace the whole content of the page, might as well do a good old hard page reload so you don't have to handle any issues regarding history, URL and so on. Of course, if you want to replace some parts of the page only, then htmx is perfect for that!

Closing this as the issue has been solved by the OP
