### ISSUE TITLE
SVGs with templates break the swapping process

### ISSUE THREAD

**Issue by areleu** [bigskysoftware/htmx#3059]
Hello,

I have been doing some dashboards wtih htmx/alpine and when using alpine templates inside svgs i get `htmx:swapError` using v 2.0.x which seems to be caused by calling findAll on undefined at:
https://github.com/bigskysoftware/htmx/blob/f946dbd8765de2f1baadd56ce674c6e047c59be3/src/htmx.js#L1817

This does not happen in 1.9.x, here is a minimal example to reproduce

```python
from fasthtml.common import serve, H1, Script, Div, fast_app
from fasthtml.svg import Svg, G, Template, Circle

alpinejs = Script(src="//unpkg.com/alpinejs", defer=True)
htmx = Script(
    src="https://unpkg.com/htmx.org@2.0.3/dist/htmx.js"
)  # this version breaks!  for this to work 1.9.12
app, rt = fast_app(
    live=True, htmx=False, hdrs=[htmx, alpinejs, Script(src="script.js")]
)


@app.get("/")
def home():
    return (
        H1("Hello world 2"),
        Div(
            "Loading ...",
            hx_get="/chart",
            hx_trigger="load",
            hx_swap="innerHTML",
            **{
                "x-data": "{ foo: true }",
                "hx-on::before-swap": "Alpine.stopObservingMutations()",
                "hx-on::after-swap": "polyfillTemplates(event.target); Alpine.initTree(event.target); Alpine.startObservingMutations()"
            },
        ),
    )


@app.get("/chart")
def chart():
    return Svg(
        Template(
            G(Circle(r=10, cy=10, fill="red", **{"x-bind:cx": "i"})),
            id="chart",
            **{"x-for": "i in [10,40,80, 150]", ":key": "i"},
        )
    )


if __name__ == "__main__":
    serve()

```

```javascript
window.polyfillTemplates = function(parent) {
            console.log("Running polyfill")
            var templates = document.querySelectorAll('svg template');
            console.log(templates)
            var el, template, attribs, attrib, count, child, content;
            for (var i=0; i<templates.length; i++) {
              el = templates[i];
              console.log(el)
              template = el.ownerDocument.createElement('template');
              console.log(template)
              el.parentNode.insertBefore(template, el);
              attribs = el.attributes;
              count = attribs.length;
              while (count-- > 0) {
                attrib = attribs[count];
                template.setAttribute(attrib.name, attrib.value);
                el.removeAttribute(attrib.name);
              }
              el.parentNode.removeChild(el);
              content = template.content;
              
              while ((child = el.firstChild)) {
                console.log(content)
                content.appendChild(child);
              }
            }
            console.log("Finished polyfill")
          };
```

The polyfill is based on the one from: https://github.com/alpinejs/alpine/discussions/3690 
Thanks in advance!

**Comment by MichaelWest22** [comment]
Yeah this is a fiddly one.  managed to repro it in a complex jsfiddler.  It seems to me the issue htmx is having is the same that alpine has with this template being inside a svg which just seems to be not valid via the html browser spec.  This seems to be what the polyfill is trying to solve as well by recreating the template as a real template with the original data.  When I inspect the template element inside the fragment that htmx is trying to process the template is just missing its template fragment content property which is then breaking the htmx code here

https://github.com/bigskysoftware/htmx/blob/2e59a142138b12d408dad02e304abe0046372ecc/src/htmx.js#L1890-L1896

htmx since v2 now supports processing oob swaps inside template fragments which is why these broken templates are breaking only v2 of htmx.

From my testing adding a null/undefined check before processing the template.content solves the issue so raised a quick PR for this.

@areleu are you able to re-test your application with this branch of htmx.js to confirm if this resolves not just your error message but you are then able to process svg templates in alpine? 
https://raw.githubusercontent.com/bigskysoftware/htmx/fba483b4773f87db3babbfcdc289499ae2b601ab/src/htmx.js

**Comment by MichaelWest22** [comment]
https://jsfiddle.net/Latent22/jc4tr2bk/1/ here is my repro.  one issue I had is demo.htmx.org script is only v1 htmx and we need a demo-v2.htmx.org to make it easier.

**Comment by areleu** [comment]
> @areleu are you able to re-test your application with this branch of htmx.js to confirm if this resolves not just your error message but you are then able to process svg templates in alpine? [`fba483b`/src/htmx.js (raw)](https://raw.githubusercontent.com/bigskysoftware/htmx/fba483b4773f87db3babbfcdc289499ae2b601ab/src/htmx.js)

This branch works! Thanks

> But getting this polyfill into htmx for this edge case seems unlikely.

I agree, since templates are not part of the SVG specification (and it has `defs` for such cases), it would do more damage than good, I think. But this fix is good enough for what I and other people doing data viz probably need, thanks! :)

**Comment by MichaelWest22** [comment]
that documentation you link to lists many attributes that are supported and expected on defs so I don't think this is a valid concern.  Sure other real SVG elements list more supported attributes because you should not be putting most normal SVG attributes on the defs element itself but the attributes you need to place are either things like id which is in spec or custom attributes like alpine ones which are the same low risk as placing them on other svg elements.

**Comment by areleu** [comment]
You are right, I was focusing too much on the description. Sending defs is definitely the cleaner way to do this, for the record I just tested opening such a file in inkscape:

```svg
<svg height="140" width="500" xmlns="http://www.w3.org/2000/svg">
    <defs x-data="{ foo: true }"></defs>
    <g>
        <defs x-data="{ bar: true }">
            <defs x-if="bar"></defs>
        </defs>
    </g>
    <ellipse cx="120" cy="80" rx="100" ry="50" style="fill:yellow;stroke:green;stroke-width:3" />
</svg>
``` 
Even with nested elements and got no issues.

**Comment by 1cg** [comment]
fixed w/ https://github.com/bigskysoftware/htmx/pull/3064 thank you!
