### ISSUE TITLE
CSP nonces are provided but are not used

### ISSUE THREAD

**Issue by RokLenarcic** [bigskysoftware/htmx#3063]
I have a script element at the top of the body with this code:
```
htmx.config.inlineStyleNonce = cspNonce;
htmx.config.inlineScriptNonce = cspNonce;    
``` 

Features that use ad hoc scripts or styles fail the CSP policy still. E.g. if I specify:

```
hx-trigger="keydown[this.value.length > 3] delay:1s"
```

Or any similar thing I get:
```
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'nonce-8FNQvl1fOTxbpTb1NxX7VA' 'sha256-mcfQU7mj4I8DxpNvzWfgM2ds2zuLt5CKHFORq+JMIvE='".
Function
(anonymous function) — htmx-2.0.3.min.js:1147
rt — htmx-2.0.3.min.js:1146
st — htmx-2.0.3.min.js:1216
lt — htmx-2.0.3.min.js:1288
kt — htmx-2.0.3.min.js:1737
(anonymous function) — htmx-2.0.3.min.js:1762
se — htmx-2.0.3.min.js:327
Dt — htmx-2.0.3.min.js:1761
(anonymous function) — htmx-2.0.3.min.js:3364
```

I was expecting that the nonce I added to settings were to be used when making these scripts.

**Comment by MichaelWest22** [comment]
With CSP script-src the nonce is used for inline scripts.  But many of the htmx advanced features use javascript to do eval() on an attribute string and this is different than inline scripts.  If you want to use htmx's eval features then your csp has to have unsafe-eval in the script-sec policy.  There is a htmx config setting you can use to disable eval use in htmx but this will just prevent htmx throwing CSP errors but these eval based functions will not work anymore.

If you can't allow unsafe-eval in your CSP then most of these functions can be replaced with custom vanilla JS event listeners but it is less convenient than using htmx attributes sometimes.

**Comment by RokLenarcic** [comment]
Do you have an example how I could replace `this.value.length > 3` with some alternative?

**Comment by MichaelWest22** [comment]
Yeah there are so many ways to do it with vanilla JS and I'm no JS wizard myself but here is a quick dirty example

```html
<input hx-trigger="my-event-name">
```

```javascript
document.body.addEventListener('keydown', function(evt) {
    if (evt.srcElement.nodeName == 'INPUT' && evt.srcElement.value.length > 3) {
        htmx.trigger(evt.srcElement,'my-event-name');
    }
});
```
This simple event listener on the body just monitors all keydown events and if they are for inputs with length > 3 triggers a custom event name which you can listen to on the input element to trigger a hx request. You can add the event listener to the input element by finding the id of the input instead of using body if you want.

If you don't like embedding so many event listener scripts in page script tags there is the option in htmx to write your own custom htmx extensions to encapsulate your custom JS which makes linking to elements fit well with htmx.

**Comment by RokLenarcic** [comment]
Ok it seems that htmx itself cannot be CSP compatible here, so I'll have to do a hack like you describe there.
