### ISSUE TITLE
Init with browser back button

### ISSUE THREAD

**Issue by constantinjoly** [bigskysoftware/htmx#310]
Please I would need some help: (JS beginner)

I use `hx-boost` to navigate between pages, these pages use some JS (intersectionObserver) to animate elements on scroll.

I "init" my scripts with `htmx:afterSettle` (I still have to check if it the best way, but actually works correctly in site navigation with links) but if the browser back button is used, animations are lost.

What would be the best way to init again my scripts with back button and htmx?

**Comment by constantinjoly** [comment]
Ok, seems that `htmx.onLoad` is the good way to do it.

**Comment by 1cg** [comment]
Yep, that's the right spot.  I made a fix in 1.1.0 to this, so please use the latest release, and let me know if you have any issues.  I want to get this area firmed up and better documented.

Your work here: https://twitter.com/cjlabfr/status/1346428024502300673  is incredible!  I would love to incorporate what you've done into the documentation for htmx, since you are really pushing the htmx swapping model to the max.

**Comment by constantinjoly** [comment]
Happy to know you like project. Yes sur, I can share it with you if it can be useful for the htmx documentation. 

This project has some  issues common to all sites that could be useful to explain and facilitate the handling of htmx and highlight how htmx solves them easily.

But first I have to solve some of these issues that I had not thought of, for exemple: deal with the browser back button when the menu is opened :( But I think it comes more from my skills in JS than anything else... even if `htmx:beforeHistorySave` may help me with that.

Also I would be happy to talk with you about #141. Please feel free to contact me by email.
