### ISSUE TITLE
How this project is different from turbo.hotwire.dev?

### ISSUE THREAD

**Issue by frederikhors** [bigskysoftware/htmx#364]
Thanks for this amazing project!

Can I ask you how this project is different from https://turbo.hotwire.dev/?

Is there a "Comparison" page?

Thanks again!

**Comment by 1cg** [comment]
Hi there,

I outlined the differences a bit here in the hotwire discussion site:

https://discuss.hotwire.dev/t/hotwire-vs-htmx-comparison/1614/3

Broadly, hotwire is more "progressive enhancement" oriented, whereas htmx is more oriented towards completing HTML as a hypertext.  I would expect htmx to be more flexible and go further before it was necessary to resort to javascript, but also to be a bit more work up front since it is more explicit in the DOM.
