### ISSUE TITLE
Clarification on hx-ws 'message' event?

### ISSUE THREAD

**Issue by KenWhitesell** [bigskysoftware/htmx#552]
I've been playing around with hx-ws integrating it with Django Channels. Right now I have a working prototype of the basic Channels chat tutorial (https://channels.readthedocs.io/en/latest/tutorial/index.html).
That tutorial sends the chat message through the socket as a json dict.

1. It appears as if the 'message' event handler is expecting the websocket message to be _only_ html, and not html within some other type of structure. 
This seems like it has the side-effect of precluding any option / possibility to handle the hx-headers on the connect. (Thinking specifically of hx-trigger here.) Or even possibly on any subsequent frame...

2. I wrote an extension providing a tranformResponse function. It extracts the html from a json dict, does other stuff with the other data, and returns that html from the function as the "text" return value. It was easy enough to do - and works. I'm mostly curious to find out if that would be the "recommended" way of handling this or if I'm missing something else.

**Comment by rtpm** [comment]
I've played with SSE today and so far only HTML string data without any structure could actually be used to replace my DOM element because If server event had any structure it's been fully returned to the swapped element. I am curious what is the best way to handle these non html or html as a value for key structures.

By the way it would be great to mention in the docs that hx-swap can be used in hx-sse and websockets so the content can be appended/prepended etc. and not just replaced.

Thanks!

**Comment by 1cg** [comment]
Hi Ken and rtpm, yes, that's right, both WebSockets and SSE expect HTML messages.  I didn't want to invent another standard to be implemented.  Your approach of writing an extension with a `transformResponse` is exactly right, and you could implement some of the htmx header support with whatever format you'd like there.

Kind of a tough area for the library, any thoughts you both have are welcome.

**Comment by KenWhitesell** [comment]
Thanks for the affirmation - I'm good with that. (This being my first playing around with htmx, I'm still just getting my feet wet.)
