### ISSUE TITLE
HX-Trigger header and redirect responses

### ISSUE THREAD

**Issue by claudep** [bigskysoftware/htmx#561]
I'm trying to set an HX-Trigger header to a response after some form POSTing. But as the response is a 302 redirect, which I learnt is a best practice after successful posting, I guess the browser is immediately redirecting and probably htmx is getting the new GET response, but without the header.

Is that analysis correct? If yes, what would you suggest? Responding directly with the final 200 response?

Depending on your response, I think it would be worth adding some note about that in the `/headers/hx-trigger/` section of the documentation.

**Comment by 1cg** [comment]
yes, because htmx uses AJAX, there is no need to issue a 302 redirect after an update, because the request will not end up in the browser history.  The original need for a 302 was to prevent users from accidentally re-issuing the update by refreshing a page, which is not an issue w/ htmx.

I agree this needs documentation somewhere, I will look into it.
