### ISSUE TITLE
Examples: Example for integrating the Sortable library is incorrect

### ISSUE THREAD

**Issue by ianastewart** [bigskysoftware/htmx#612]
In the example code for working with sortable.js, each div in the form contains a hidden input with the same name, but different value. The intention is that all those inputs are posted to the server in the sorted sequence, but because the name attributes are identical, only the last input actually gets posted.

**Comment by 1cg** [comment]
All the values are posted to the server:

![image](https://user-images.githubusercontent.com/469183/136660847-d3b6407e-6cd8-46b3-a8aa-3fa5b8854d4e.png)

What are you using on the server?  Is it possible the server-side software you are using may treat multiple values for a parameter as one?  There may be a different mechanism rather than the standard parameter access that allows you access to all values for a given parameter.

**Comment by 1cg** [comment]
Looks like the getlist method might be what you want:

https://pythoncircle.com/post/710/getting-query-params-from-request-in-django/
