### ISSUE TITLE
https://htmx.org/examples/inline-validation/ broken

### ISSUE THREAD

**Issue by jaens** [bigskysoftware/htmx#62]
Repro:
* enter "what" into the e-mail field
* click "submit"

That just causes another "Signup Form" header to appear.

**Comment by agraddy** [comment]
If you enter "what" and then press `<tab>`, the validation should work. In a real life example, the server would also return an error if the email was not valid. That should probably be cleaned up since it appears broken in the example using the steps you listed.

It looks like the reason "Signup Form" duplicates every time the form is submitted is because the `<h3>Signup Form</h3>` is outside the `<form>` tag. So whenever the form is submitted the `<form>` gets replaced but the original `<h3>` is there with a new one added.

**Comment by chg20** [comment]
thank you again @agraddy I have improved the demo based on your comments

**Comment by szepeviktor** [comment]
@chg20 Your commit are made with a git client not configured for your GitHub account
