### ISSUE TITLE
Option to follow 302 redirects

### ISSUE THREAD

**Issue by demestav** [bigskysoftware/htmx#632]
Currently when the server responds with a 302 redirect to a request made by htmx, the response is swapped in the target. If the desired effect is for the browser to follow this redirect and refresh the page, then the `HX-Redirect` header must be passed in the response with status code 200.

This works fine but requires building this specific behavior (200 code + `HX-Redirect` header) server side.

An htmx parameter (client-side) would make this workflow much easier, and won't require any change on the server side. Is something like this possible at the moment? If not, would you consider adding it?

**Comment by 1cg** [comment]
`302` redirects should be handled by the browser, and htmx shouldn't see this response.  

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302

htmx should only see the final values.

**Comment by jartaud** [comment]
Adding `hx-push-url="true"` to the form did the trick.

**Comment by jsonberry** [comment]
I was having `redirect` issues with `form` POSTS, where my `location` and `push history` wasn't updating like I expected.... and `hx-push-url="true"` on the `form` also adjusted the behavior for me to match what I was expecting.

the flow was on a form doing an hx-post and at the endpoint I setup a redirect, the redirect would work, but push state wouldn't follow... and with `hx-push-url`, we gucci

**Comment by TonisPiip** [comment]
another related issue to this: https://github.com/bigskysoftware/htmx/issues/2052

**Comment by woutrbe** [comment]
I wanted to understand this a bit better, as you mentioned, when sending a 3xx redirect from the server, htmx ignores this. Sending a 2xx response does work, and htmx seems to respect the `hx-redirect` headers.

However if I were to disable javascript, this would now break my application as the server is just responding with a 2xx response, instead of the required redirect. How would you suggest fixing this?

I was hoping I could just use htmx to slightly improve the UX of certain forms, but instead now I have to write specific use-cases when htmx is in use, and when not.

**Comment by Telroshan** [comment]
You could probably check the [HX-Request header](https://htmx.org/reference/#headers) server side ; if it's there, the request was made by htmx, thus JS is enabled on this client and you can do the 2xx response code trick, otherwise return a standard redirection

**Comment by woutrbe** [comment]
Using the `HX-Request` header does the job;

```
return req.headers['hx-request'] ?
      reply
	      .header('HX-Redirect', `/t/${defaultCompany.uuid}/c/new`)
	      .code(200).send() :
      reply
	      .redirect(303, `/t/${defaultCompany.uuid}/c/new`);
```
