### ISSUE TITLE
Modal popup div ?

### ISSUE THREAD

**Issue by albert-kam** [bigskysoftware/htmx#64]
Very very excited about htmx just from reading about it. I have been thinking about my usual needs in developing backoffice applications, and modal popup form comes to mind.

For example, when a user wants to enter a sales order, but halfway through, it turns out the customer hasnt been entried into the system, or the address might have changed for that customer. 

Usually i just open up a modal popup dialog displaying the customer form, enabling the user to create a new customer record or to add the new address, and after that returning to the main form to resume the data entry. 

I'm curious on how to implement this approach with htmx ?

Thank you !

**Comment by Lockhead** [comment]
Wouldn't that be only a separate form and the rest is CSS and HTML to style it like a modal?

**Comment by agraddy** [comment]
I'm just checking out htmx myself so not sure if this is the recommended way, but it seems like you could use something like the Click To Edit example:
https://htmx.org/examples/click-to-edit/

But instead of targetting "this", you could target a popups section. Something like this (roughed out code that is not tested and may not work):
```
<div id="contact" hx-target="#popups">
    <div><label>First Name</label>: Joe</div>
    <div><label>Last Name</label>: Blow</div>
    <div><label>Email</label>: joe@blow.com</div>
    <button hx-get="/contact/1/edit" class="btn btn-primary">
    Click To Edit
    </button>
</div>
<div id="popups">
</div>
```

And then have the server respond with this which gets placed in the #popups div (use CSS to show the modal):
```
<div class="popup show">
<form hx-put="/contact/1" hx-target="#contact" hx-swap="outerHTML">
  <div>
    <label>First Name</label>
    <input type="text" name="firstName" value="Joe">
  </div>
  <div class="form-group">
    <label>Last Name</label>
    <input type="text" name="lastName" value="Blow">
  </div>
  <div class="form-group">
    <label>Email address</label>
    <input type="email" name="email" value="joe@blow.com">
  </div>
  <button class="btn">Submit</button>
  <button class="btn" hx-get="/close-popup">Cancel</button>
</form> 
</div>
```

You could have the Cancel button contact /close-popup which would return this and basically close/remove the popup:
```
<div is="popups" hx-swap-oob="true"></div>
```

You could have the PUT to /contact/1 do the same thing when you submit the form. Have the response includes an hx-swap-oob to close the popup.

The cancel button hitting a /close-popup endpoint feels a little messy to me (an alternative is maybe just add some javascript to remove the poup). Also instead of using hx-swap-oob, you could possible create an extension that if on a response if a popup is visible, close the popup. 

I haven't tested any of this, but I believe this should work.

**Comment by chg20** [comment]
Hi guys,

Yes, there are many ways to skin this cat.  One approach I have been taking more and more is to stop thinking about a "popup" and just inline the popup in the ui, more like a wizard.  This introduces less state in the DOM (you can even push a new URL to allow the user to copy and send it to someone else) and has ended up feeling more "webish" when I do it.

@agraddy 's approach looks great as well.

Just depends on how you want to tackle it.
