### ISSUE TITLE
Passing a CSRF token in the request header

### ISSUE THREAD

**Issue by fdeage** [bigskysoftware/htmx#70]
Hey, really like HTMX, nice job!
However I can't figure out how to pass my CSRF token in the request headers (or to actually configure headers at all).

It's strange because I used intercooler before, and I never had a missing CSRF token...

EDIT: I'm using Elixir/Phoenix

**Comment by chg20** [comment]
Hi There,

Huh, seems like it should "just work" with rails forms, unless we aren't including hidden inputs properly....

**Comment by rschroll** [comment]
If you're not using form submissions, you can insert the CSRF token into all htmx requests with a bit of JS.  Here's what I have in a Django template:
```
document.body.addEventListener('configRequest.htmx', (event) => {
    event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
})
```

**Comment by fdeage** [comment]
Thanks for your reply.
It's weird but this event is never triggered...

**Comment by rschroll** [comment]
I'm afraid the best advice I can give is to enable logging (https://htmx.org/docs#events).  This may help us see if the events are getting gobbled up by some other handler.

Maybe someone else has more insight.

**Comment by chg20** [comment]
Hey fdeage, I have added another plugin that does something similar to what you want here:

https://github.com/bigskysoftware/htmx/commit/2305aed18e925da55f15dc5798db37ac0142f2b4

That code should definitely work for what you are trying to do.

**Comment by fdeage** [comment]
Thanks @chg20, I'll give it a try!

**Comment by mblayman** [comment]
For readers as of 2021, I followed @rschroll's suggestion, but the event is renamed in the version that I'm using (1.1.0 at the time of this comment):

```javascript
document.body.addEventListener('htmx:configRequest', (event) => {
  event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
})
```

Thanks @rschroll!

**Comment by srkunze** [comment]
@mblayman I just wanted to add for Django adding this code snippet should be placed at the end of `body`. (at least it didn't work for me when placed ìn `head`.

**Comment by sasha-co** [comment]
> For readers as of 2021, I followed @rschroll's suggestion, but the event is renamed in the version that I'm using (1.1.0 at the time of this comment):
> 
> ```js
> document.body.addEventListener('htmx:configRequest', (event) => {
>   event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
> })
> ```
> 
> Thanks @rschroll!

It probably should be `X-CSRF-Token` instead of `X-CSRFToken`, but the idea is there and it works.

**Comment by TracyGJG** [comment]
@1cg, One of HTMX's biggest selling points for a many developers is the reduced/eliminated need for JavaScript to support interaction with the backend. I am disappointed that the recommended approach requires just that.

I am also very surprised the official documentation has nothing to say about CSRF protection. 

Although not an authoritative text, I was initially hopeful for the solution documented in the [Little HTMX Book (security)](https://littlehtmxbook.com/#security-considerations) with the CSRF token injected by the server into a meta tag, which would be automatically picked up and included in all subsequent requests. But this doe not appear to be supported.

I appreciate this issue is now closed so my requests might go unanswered but here goes:

1. Could we please have an authoritative statement on how HTMX recommends developers establish CSRF protection.
2. Could we consider the potential for implementing the meta tag approach described above, which provides a cleaner approach.

**Comment by Telroshan** [comment]
Hey @TracyGJG , since this issue, the attribute [hx-headers](https://htmx.org/attributes/hx-headers/) has been added to the library, which should fit your usecase here. This attribute is inherited by default so you could likely put it on your body tag and have all your htmx requests include your CSRF header (unless an element explicitly override this attribute's value ofc)

Hope this helps!

PRs to improve documentation are always welcome btw, mentioning a typical CSRF setup could surely be useful for other people as well!

**Comment by TracyGJG** [comment]
@Telroshan, Thank you for your prompt and informative response to my query. The [hx-headers](https://htmx.org/attributes/hx-headers/) is exactly the sort of mechanism I was hoping to find and meets my use case perfectly. 

For the benefit of anyone else after this feature: I have found adding the `hx-headers` attribute to either the `html` or `body` tag ensures all HTTP requests from the document include the `csrf-token`.

I have now forked the htmx repo with the intention of providing a PR to update the documentation to help others.
