### ISSUE TITLE
HTMX breaks command + click

### ISSUE THREAD

**Issue by thekashifmalik** [bigskysoftware/htmx#721]
I've noticed that HTMX-fied links no lo longer let you command click to open in a new tab. This seems surprising.

Does it makes sense to manually handle that for links by default?

**Comment by waldyrious** [comment]
I just came here to report that the logo in the htmx website doesn't allow Ctrl+click to open in a new tab.

However, I'm not sure if that one counts as an "HTMX-fied link":

https://github.com/bigskysoftware/htmx/blob/e3c0dadbe7de09fde4df32fb7d730ab8385379b4/www/_includes/layout.njk#L30

Happy to open a separate issue if it is indeed unrelated.

**Comment by waldyrious** [comment]
For the record, I am able to Ctrl+click [hx-boosted](https://htmx.org/attributes/hx-boost/) links, such as the ones in the website's navbar: 

https://github.com/bigskysoftware/htmx/blob/e3c0dadbe7de09fde4df32fb7d730ab8385379b4/www/_includes/layout.njk#L40-L44

...and have them open in a new tab. If it helps, I'm using Firefox 95.0 on Ubuntu 20.04.

**Comment by gmso** [comment]
Hi,

I believe the problem is that DOM elements with an `hx-get` attribute are not considered links by the browser. Therefore, the _Ctrl+Click_ command does not open the new route in a new tab, as it usually does with regular links using `<a>` tags.

Related to that, what @waldyrious mentions seems to show that even boosted `<a>` tags have this behavior (like in the website's navbar) but not other HTML tags with an `hx-get` attribute (like in the website's logo). Interestingly enough, if you change the website's logo element from a `<span>` to a normal `<a>` tag pointing to the root, the _Ctrl+Click_ behaviour works as expected. So from:
```html
<span hx-get="/" hx-target="body" hx-push-url="true" class="logo light"> ... </span>
```
To:
```html
<a class="logo light" href="/"> .... </a>
```

With this change I can _Ctrl+Click_ and get a new tab with the root page. This seems to work with Firefox 95.0.2 and Chrome  96.0.4664.110. I haven't tested any other browsers.

For me, the rule of thumb would be to use boosted `<a>` tags when you want to point to a different page/route within your site, and `hx-get` attributes when you want to dynamically fetch data from the server, but you want to stay inside the same page/route

**Comment by benpate** [comment]
My bet is that your browser is adding extra logic into `<a>` tags to filter control+click (and right clicks, too) that they do not provide to `<span>` and other non-interactive elements.  You could look into additional options in the [hx-trigger](https://htmx.org/attributes/hx-trigger/) attribute as a possible workaround (for instance, `hx-trigger="click[!ctrlKey]"`) but this is a hack on top of a hack.

For many reasons, including this one, it's probably best to only attach actions to elements that your browser expects to be interactive: `<a>`, `<button>`, `<input>`, etc.  Putting interactive actions on `<span>`s and the like constitutes the "nightmare of accessibility" that plagues most front-end javascript.  If it's clickable, make it a button.  If it takes you somewhere else, make it a hyperlink.  Stylesheets and WAI-AIRA annotations can pick up the rest.

**Comment by 1cg** [comment]
agree w/ ben here

**Comment by waldyrious** [comment]
@1cg if you agree, then the logo on the htmx.org website ([quoted above](https://github.com/bigskysoftware/htmx/issues/721#issuecomment-997193705)) should change from a `<span>` to an `<a>`, as @gmso [suggested](https://github.com/bigskysoftware/htmx/issues/721#issuecomment-1001189171), right?

**Comment by thekashifmalik** [comment]
This sounds reasonable to me.

My original issue was that `<a>` links with an `hx-get` attribute but not an explicit `href` attribute were not working correctly (regarding `ctrl+click`). Looks like browsers don't handle links the same when they are missing an `href` attribute, which sort of makes sense but is confusing when you're starting out with `htmx` (and only using `hx-get`).

I resolved this issue (after talking to @1cg on Discord) by setting `hx-boost` on the body and only the `href` attribute on links. This works both semantically and technically.

+1 on @waldyrious's comment

**Comment by waldyrious** [comment]
For the record, the change of the home link from a `<span>` to an actual `<a>` was done in 023b7cb2a by @dz4k.
