### ISSUE TITLE
Option to specify "swap" value when using htmx.ajax()

### ISSUE THREAD

**Issue by rogue26** [bigskysoftware/htmx#791]
As far as I can tell, it's not currently possible to specify an equivalent to hx-swap when using the htmx.ajax() javascript API documented  [here.](https://htmx.org/api/#ajax). It's got target, values, etc. but no swap.

My current workaround is to specify the default swap style with a meta tag, but it would be nice to have the flexibility within the API. If this is already possible, I'd love to know how to do it.

PS - Thank you for creating HTMX.

**Comment by aymericderbois** [comment]
I don't know if the doc has been updated since your message, but there is an example with swap.

```js
htmx.ajax('GET', '/example', {target:'#myDiv', swap:'outerHTML'})
```

**Comment by ThibH** [comment]
I recently tried to use `htmx.ajax` as well and used the swap key as indicated in the documentation, with a value of "none" since I didn't want any swapping to happen, but it didn't work.

Workaround I found was to return a 204 - No Content response in my Django view :
`return HttpResponse(status=HTTPStatus.NO_CONTENT)` (as explained [here](https://htmx.org/docs/#requests)).

**Comment by David-Guillot** [comment]
Hi @rogue26 ,

It seems #769 fixed your issue the day after you posted it. Can you make sure it works as expected with htmx 1.7.x?

**Comment by gone** [comment]
@ThibH can you clarify what you expected? You wanted to return html from the server and have htmx throw it away vs use it? 

Why use htmx's ajax over fetch in that case?

**Comment by ThibH** [comment]
@gone Yes that's what I wanted and to answer your question it really is just because I am already using htmx for everything so I got really used to it. I might as well use fetch for sure, but if it can be done with htmx, I find it easier this way :)
