### ISSUE TITLE
Combine `closest` and `find` for `hx-target`

### ISSUE THREAD

**Issue by peterhijma** [bigskysoftware/htmx#814]
If this is already possible, it's not clear to me how :)

But would it be possible to combine `closest` and `find`?

This would allow to handle these cases, without specifying an `id` or custom class for every `div`:

```html
<div class="container">
   <input hx-get="..." hx-trigger="..." hx-target="...">
   <div class="target"></div>
</div>

<div class="container">
   <input hx-get="..." hx-trigger="..." hx-target="...">
   <div class="target"></div>
</div>
```

Thanks in advance.

**Comment by David-Guillot** [comment]
Hi there,

I am actually not sure what you are trying to achieve here: do you want these two divs to cross/exchange their targets? If so, could you elaborate on your use case please? Because the solution would be different whether the number of divs is fixed or not.

At first sight, `closest` and `find` can't be combined because they have opposite effect: the former searches up to the DOMs root, while the latter searches down from the current element. But according to your use case, maybe some smart CSS selector would do the trick 😉

**Comment by 1cg** [comment]
Hi there.  What you want is `next .target`, a concept taking from hyperscript.  I have added this functionality to htmx and it will be available in the next (lol) release.  :)
