### ISSUE TITLE
browser history API:

### ISSUE THREAD

**Issue by Philkobby** [bigskysoftware/htmx#884]
Using Alpine Js to load data via API requests and browser history API is loading already loaded fetched data in addition to the API request.
instead of the initial data been an empty array until the data is fetched from the API.

**Comment by David-Guillot** [comment]
Hi there,

Could you please be a bit more specific? Like:
* How is htmx involved in your issue?
* How does it interact with Alpine?
* Elaborate about the expected behavior and the actual behavior?

Maybe show us a piece of code would help :wink: .

Alternatively if you're not sure if there is an issue, and you need some help instead, you could try htmx's Discord, which has [a channel](https://discord.com/channels/725789699527933952/931549069141225613) dedicated to htmx/AlpineJS interaction :wink:

**Comment by Philkobby** [comment]
so I have a users page, I use Alpine Js to fetch the data from API each time the page load. now when I use htmlx to navigate to a different page and hit the browser back button, it loads the page with a list of users previously rendered in addition to the fresh api request.
Am wondering if I can stop htmlx from loading that page from the cache. kind of making htmlx treat the browser back and forward button as a fresh request instead of loading from the cache

**Comment by David-Guillot** [comment]
Hm. If you allow me, here's some web architecture advice:
- If you want to keep your API involved in generating your web pages (because your templates are in your JS code), you can just drop htmx, as it was meant to avoid the complexity of client-side application state management
- If you want to embrace htmx philosophy (manage application state on server side ; use JS for pure client-side stuff), you can drop your API and have your server generate HTML fragments (partial templates), and use AlpineJS for other purposes
- htmx and AlpineJS can play nice with each other in the following architecture: htmx used to communicate with the server in order to load page fragments, AlpineJS used to trigger pure client-side interactions (web components, etc.)

That being said: if you want to persist that way, you can always [configure htmx to have no history cache](https://htmx.org/docs/#config).

**Comment by Philkobby** [comment]
Thanks @David-Guillot 
Am grateful
