### ISSUE TITLE
How to retain the form after submit

### ISSUE THREAD

**Issue by ljfreelancer88** [bigskysoftware/htmx#896]
After form submit, my back-end `controller` fetch the new comment created. But instead of appending the new created record to `.comment-future` element. It redirects to the partial `view` for newly created record.

What I want is retain the form after submit, then append the new record. How can I achieve this in htmx way? Thank you in advance.

```html
<div id="comment">
  <div class="comment-child">
  ...
  </div>
  <div class="comment-future"></div>
</div>

<form action"/comment" data-hx-post="/comment" data-hx-target=".comment-future" method="POST">
...
</form>
```

**Comment by gone** [comment]
Use https://htmx.org/attributes/hx-swap/ and before end to append the record. 

If you are seeing the entire page change then double check htmx is loaded correctly - a good way to test would be to remove the action and method attributes from the form and see what happens when submitting. If htmx is catching it you'll see a post, if htmx isn't set up correctly you'll see a get

**Comment by ljfreelancer88** [comment]
I added `hx-trigger = "click"` in my form which is the doing the "preventDefault", which is okay. But another problem is when I click on the textarea with no value. It sends a request on the server (based on the console). Is there any way to tell htmx that listen to button event only.

**Comment by ljfreelancer88** [comment]
I ended up adding `'onsubmit' = "event.preventDefault();"` on the form.

Final solution...
```html
<form action"/comment" 
    data-hx-post="/comment" 
    data-hx-target=".#comment" 
    data-hx-swap="beforeend" 
    method="POST" onsubmit="event.preventDefault();">
...
</form>
```

I hope there's an htmx way to do it.
