### ISSUE TITLE
hx-val array handling

### ISSUE THREAD

**Issue by mlthlschr** [bigskysoftware/htmx#966]
Currently, if I try to add an object containing an array on the first level to `hx-val`, the value is discarded and not added to the parameters of the call.

Example:
```json
{
  "firstLevel": [1,2,3],
  "secondLevel": {
    "values": [4,5,6]
  }
}
```

Here, it fails due to the `firstLevel` field ("Multiple values for one key: \"firstLevel\""))
The `secondLevel` field would be accepted, as the whole objects gets passed as JSON.

Maybe arrays could be interpreted the same way as objects are.

**Comment by Telroshan** [comment]
Hey, I know this is an old issue, but trying this with latest htmx version (2.0.2 here) seems to give the expected result on [this JSFiddle](https://jsfiddle.net/su0mwerd/), unless I missed something?
![image](https://github.com/user-attachments/assets/290fd732-35d2-4c2e-a5fa-7e1b9fb342bf)

As for your issue @HiroDane, it seems by what you describe that you'd like the data to stay in JSON format, in which case you'll probably want to use the [`json-enc`](https://github.com/bigskysoftware/htmx-extensions/blob/main/src/json-enc/README.md) extension, as htmx will use FormData and send URL-encoded values by default (like a standard HTML form).
Note that we had a [recent fix](https://github.com/bigskysoftware/htmx-extensions/commit/594a21a89080b09cbcc6d7ba4c83af30f1ef0c0e) for that extension, precisely about hx-vals. Extension should be published with a new version soon, but you can always use the repo's file instead of linking it from unpkg if you need it asap.

Also, please note that bugfix PRs are always welcome, so if you feel like work is too slow on a given issue, you can always try to setup a PR yourself, help is always greatly appreciated when it comes to fixing bugs.

Hope this helps!

**Comment by 1cg** [comment]
closing, please reopen if this is still an issue
